/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_parser.check" instead.
 */

#include <check.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "parser.h"
#include "s21_matrix.h"

START_TEST(test_2) {
  Gigachad test = {0};
  char path[255] = {0};
  getcwd(path, sizeof(path));
  int size = strlen(path) + 1;
  strcat(path, "/cube.obj");
  path[size + 8] = '\0';
  parseObjFile((const char *)path, &test);
  ck_assert_float_eq(test.vertices[0], 0.0f);
  ck_assert_float_eq(test.vertices[1], 0.0f);
  ck_assert_float_eq(test.vertices[2], 0.0f);
  ck_assert_float_eq(test.vertices[3], 0.0f);
  ck_assert_float_eq(test.vertices[4], 0.0f);
  ck_assert_float_eq(test.vertices[5], 1.0f);
  ck_assert_float_eq(test.vertices[6], 0.0f);
  ck_assert_float_eq(test.vertices[7], 1.0f);
  ck_assert_float_eq(test.vertices[8], 0.0f);
  ck_assert_float_eq(test.vertices[9], 0.0f);
  ck_assert_float_eq(test.vertices[10], 1.0f);
  ck_assert_float_eq(test.vertices[11], 1.0f);
  ck_assert_float_eq(test.vertices[12], 1.0f);
  ck_assert_float_eq(test.vertices[13], 0.0f);
  ck_assert_float_eq(test.vertices[14], 0.0f);
  ck_assert_float_eq(test.vertices[15], 1.0f);
  ck_assert_float_eq(test.vertices[16], 0.0f);
  ck_assert_float_eq(test.vertices[17], 1.0f);
  ck_assert_float_eq(test.vertices[18], 1.0f);
  ck_assert_float_eq(test.vertices[19], 1.0f);
  ck_assert_float_eq(test.vertices[20], 0.0f);
  ck_assert_float_eq(test.vertices[21], 1.0f);
  ck_assert_float_eq(test.vertices[22], 1.0f);
  ck_assert_float_eq(test.vertices[23], 1.0f);
  ck_assert_int_eq(test.faces[0].vertex_index[0], 1);
  ck_assert_int_eq(test.faces[0].vertex_index[1], 7);
  ck_assert_int_eq(test.faces[0].vertex_index[2], 7);
  ck_assert_int_eq(test.faces[0].vertex_index[3], 5);
  ck_assert_int_eq(test.faces[0].vertex_index[4], 5);
  ck_assert_int_eq(test.faces[0].vertex_index[5], 1);
  ck_assert_int_eq(test.faces[1].vertex_index[0], 1);
  ck_assert_int_eq(test.faces[1].vertex_index[1], 3);
  ck_assert_int_eq(test.faces[1].vertex_index[2], 3);
  ck_assert_int_eq(test.faces[1].vertex_index[3], 7);
  ck_assert_int_eq(test.faces[1].vertex_index[4], 7);
  ck_assert_int_eq(test.faces[1].vertex_index[5], 1);
  ck_assert_int_eq(test.faces[2].vertex_index[0], 1);
  ck_assert_int_eq(test.faces[2].vertex_index[1], 4);
  ck_assert_int_eq(test.faces[2].vertex_index[2], 4);
  ck_assert_int_eq(test.faces[2].vertex_index[3], 3);
  ck_assert_int_eq(test.faces[2].vertex_index[4], 3);
  ck_assert_int_eq(test.faces[2].vertex_index[5], 1);
  ck_assert_int_eq(test.faces[3].vertex_index[0], 1);
  ck_assert_int_eq(test.faces[3].vertex_index[1], 2);
  ck_assert_int_eq(test.faces[3].vertex_index[2], 2);
  ck_assert_int_eq(test.faces[3].vertex_index[3], 4);
  ck_assert_int_eq(test.faces[3].vertex_index[4], 4);
  ck_assert_int_eq(test.faces[3].vertex_index[5], 1);
  ck_assert_int_eq(test.faces[4].vertex_index[0], 3);
  ck_assert_int_eq(test.faces[4].vertex_index[1], 8);
  ck_assert_int_eq(test.faces[4].vertex_index[2], 8);
  ck_assert_int_eq(test.faces[4].vertex_index[3], 7);
  ck_assert_int_eq(test.faces[4].vertex_index[4], 7);
  ck_assert_int_eq(test.faces[4].vertex_index[5], 3);
  ck_assert_int_eq(test.faces[5].vertex_index[0], 3);
  ck_assert_int_eq(test.faces[5].vertex_index[1], 4);
  ck_assert_int_eq(test.faces[5].vertex_index[2], 4);
  ck_assert_int_eq(test.faces[5].vertex_index[3], 8);
  ck_assert_int_eq(test.faces[5].vertex_index[4], 8);
  ck_assert_int_eq(test.faces[5].vertex_index[5], 3);
  ck_assert_int_eq(test.faces[6].vertex_index[0], 5);
  ck_assert_int_eq(test.faces[6].vertex_index[1], 7);
  ck_assert_int_eq(test.faces[6].vertex_index[2], 7);
  ck_assert_int_eq(test.faces[6].vertex_index[3], 8);
  ck_assert_int_eq(test.faces[6].vertex_index[4], 8);
  ck_assert_int_eq(test.faces[6].vertex_index[5], 5);
  ck_assert_int_eq(test.faces[7].vertex_index[0], 5);
  ck_assert_int_eq(test.faces[7].vertex_index[1], 8);
  ck_assert_int_eq(test.faces[7].vertex_index[2], 8);
  ck_assert_int_eq(test.faces[7].vertex_index[3], 6);
  ck_assert_int_eq(test.faces[7].vertex_index[4], 6);
  ck_assert_int_eq(test.faces[7].vertex_index[5], 5);
  ck_assert_int_eq(test.faces[8].vertex_index[0], 1);
  ck_assert_int_eq(test.faces[8].vertex_index[1], 5);
  ck_assert_int_eq(test.faces[8].vertex_index[2], 5);
  ck_assert_int_eq(test.faces[8].vertex_index[3], 6);
  ck_assert_int_eq(test.faces[8].vertex_index[4], 6);
  ck_assert_int_eq(test.faces[8].vertex_index[5], 1);
  ck_assert_int_eq(test.faces[9].vertex_index[0], 1);
  ck_assert_int_eq(test.faces[9].vertex_index[1], 6);
  ck_assert_int_eq(test.faces[9].vertex_index[2], 6);
  ck_assert_int_eq(test.faces[9].vertex_index[3], 2);
  ck_assert_int_eq(test.faces[9].vertex_index[4], 2);
  ck_assert_int_eq(test.faces[9].vertex_index[5], 1);
  ck_assert_int_eq(test.faces[10].vertex_index[0], 2);
  ck_assert_int_eq(test.faces[10].vertex_index[1], 6);
  ck_assert_int_eq(test.faces[10].vertex_index[2], 6);
  ck_assert_int_eq(test.faces[10].vertex_index[3], 8);
  ck_assert_int_eq(test.faces[10].vertex_index[4], 8);
  ck_assert_int_eq(test.faces[10].vertex_index[5], 2);
  ck_assert_int_eq(test.faces[11].vertex_index[0], 2);
  ck_assert_int_eq(test.faces[11].vertex_index[1], 8);
  ck_assert_int_eq(test.faces[11].vertex_index[2], 8);
  ck_assert_int_eq(test.faces[11].vertex_index[3], 4);
  ck_assert_int_eq(test.faces[11].vertex_index[4], 4);
  ck_assert_int_eq(test.faces[11].vertex_index[5], 2);
  destroy_gigachads(&test);
}
END_TEST

START_TEST(s21_create_matrix_test_1) {
  int rows = 4, columns = 4;
  matrix_t A = {0};
  int res = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(res, OK);
  ck_assert_int_eq(A.rows, rows);
  ck_assert_int_eq(A.columns, columns);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_create_matrix_test_2) {
  int rows = -1, columns = -1;
  matrix_t A = {0};
  int res = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(res, INCORRECT_MATRIX);
  s21_remove_matrix(&A);
  ck_assert_int_eq(A.rows, 0);
  ck_assert_int_eq(A.columns, 0);
  ck_assert_int_eq(A.matrix == NULL, 1);
}
END_TEST

START_TEST(s21_create_matrix_test_3) {
  int rows = 0, columns = 0;
  matrix_t A = {0};
  int res = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(res, INCORRECT_MATRIX);
  s21_remove_matrix(&A);
  ck_assert_int_eq(A.rows, 0);
  ck_assert_int_eq(A.columns, 0);
  ck_assert_int_eq(A.matrix == NULL, 1);
}
END_TEST

START_TEST(s21_create_matrix_test_4) {
  int rows = 1, columns = 0;
  matrix_t A = {0};
  int res = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(res, INCORRECT_MATRIX);
  s21_remove_matrix(&A);
  ck_assert_int_eq(A.rows, 0);
  ck_assert_int_eq(A.columns, 0);
  ck_assert_int_eq(A.matrix == NULL, 1);
}
END_TEST

START_TEST(s21_create_matrix_test_5) {
  int rows = 0, columns = 1;
  matrix_t A = {0};
  int res = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(res, INCORRECT_MATRIX);
  s21_remove_matrix(&A);
  ck_assert_int_eq(A.rows, 0);
  ck_assert_int_eq(A.columns, 0);
  ck_assert_int_eq(A.matrix == NULL, 1);
}
END_TEST

START_TEST(s21_create_matrix_test_6) {
  int rows = 1, columns = 1;
  matrix_t A = {0};
  int res = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(res, OK);
  ck_assert_int_eq(A.rows, rows);
  ck_assert_int_eq(A.columns, columns);
  s21_remove_matrix(&A);
  ck_assert_int_eq(A.rows, 0);
  ck_assert_int_eq(A.columns, 0);
  ck_assert_int_eq(A.matrix == NULL, 1);
}
END_TEST

START_TEST(s21_create_matrix_test_7) {
  int rows = 25, cols = 5;
  int ret_val = s21_create_matrix(rows, cols, NULL);
  ck_assert_int_eq(ret_val, INCORRECT_MATRIX);
}
END_TEST

START_TEST(equal_test_1) {
  int rows1 = 2, cols1 = 3;
  matrix_t A = {0}, B = {0};
  s21_create_matrix(rows1, cols1, &A);
  s21_create_matrix(rows1, cols1, &B);
  A.matrix[0][0] = -565.0;
  A.matrix[0][1] = 336.0;
  A.matrix[0][2] = 387.0;
  A.matrix[1][0] = -571.0;
  A.matrix[1][1] = -625.0;
  A.matrix[1][2] = 659.0;
  B.matrix[0][0] = -564.9999999425665;
  B.matrix[0][1] = 336.00000009840676;
  B.matrix[0][2] = 386.99999991639265;
  B.matrix[1][0] = -571.0000000294291;
  B.matrix[1][1] = -624.9999999675878;
  B.matrix[1][2] = 658.9999999752287;
  int status = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(status, 1);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_eq_matrix_6) {
  int rows1 = 1, columns1 = 2;
  int rows2 = 2, columns2 = 1;
  matrix_t A = {0}, B = {0};
  s21_create_matrix(rows1, columns1, &A);
  s21_create_matrix(rows2, columns2, &B);
  int res = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(res, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_eq_matrix_7) {
  int rows1 = 2, columns1 = 1;
  matrix_t A = {0};
  s21_create_matrix(rows1, columns1, &A);
  int res = s21_eq_matrix(&A, NULL);
  ck_assert_int_eq(res, FAILURE);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_eq_matrix_8) {
  int rows1 = 2, columns1 = 0;
  int rows2 = 1, columns2 = 2;
  matrix_t A = {0}, B = {0};
  s21_create_matrix(rows1, columns1, &A);
  s21_create_matrix(rows2, columns2, &B);
  int res = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(res, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_eq_matrix_9) {
  int rows1 = 2, columns1 = 1;
  int rows2 = -12, columns2 = 2;
  matrix_t A = {0}, B = {0};
  s21_create_matrix(rows1, columns1, &A);
  s21_create_matrix(rows2, columns2, &B);
  int res = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(res, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(num_mul_test_0) {
  int rows1 = 2, cols1 = 3;
  matrix_t A = {0}, result = {0};
  s21_create_matrix(rows1, cols1, &A);
  A.matrix[0][0] = -58.0;
  A.matrix[0][1] = -50.0;
  A.matrix[0][2] = -66.0;
  A.matrix[1][0] = -94.0;
  A.matrix[1][1] = 95.0;
  A.matrix[1][2] = -67.0;
  int status = s21_mult_number(&A, 948.0939352882323, &result);
  ck_assert_int_eq(status, OK);
  ck_assert_double_eq_tol(result.matrix[0][0], -54989.448246717475, 0.0000001);
  ck_assert_double_eq_tol(result.matrix[0][1], -47404.696764411616, 0.0000001);
  ck_assert_double_eq_tol(result.matrix[0][2], -62574.19972902333, 0.0000001);
  ck_assert_double_eq_tol(result.matrix[1][0], -89120.82991709384, 0.0000001);
  ck_assert_double_eq_tol(result.matrix[1][1], 90068.92385238207, 0.0000001);
  ck_assert_double_eq_tol(result.matrix[1][2], -63522.29366431156, 0.0000001);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_mul_num_1_err) {
  matrix_t R = {0};
  int status = s21_mult_number(NULL, 2, &R);
  ck_assert_int_eq(status, 1);
  s21_remove_matrix(&R);
}
END_TEST

START_TEST(sum_test_1) {
  int rows1 = 2, cols1 = 3;
  int rows2 = 1, cols2 = 3;
  matrix_t A = {0}, B = {0};
  s21_create_matrix(rows1, cols1, &A);
  s21_create_matrix(rows2, cols2, &B);
  A.matrix[0][0] = 695.0;
  A.matrix[0][1] = 930.0;
  A.matrix[0][2] = 363.0;
  A.matrix[1][0] = -60.0;
  A.matrix[1][1] = 842.0;
  A.matrix[1][2] = -291.0;
  B.matrix[0][0] = -61.0;
  B.matrix[0][1] = -91.0;
  B.matrix[0][2] = -94.0;
  int status = move_model(&A, &B);
  ck_assert_int_eq(status, OK);
  ck_assert_double_eq_tol(A.matrix[0][0], 634.0, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][1], 839.0, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][2], 269.0, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][0], -121.0, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][1], 751.0, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][2], -385.0, 0.0000001);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_sum_matrix_2_err) {
  int rows = 3, columns = 3;
  matrix_t A = {0};
  s21_create_matrix(rows, columns, &A);
  int status = move_model(&A, NULL);
  ck_assert_int_eq(status, 1);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_sum_matrix_3_err) {
  matrix_t B = {0};
  s21_create_matrix(5, 3, &B);
  int status = move_model(NULL, &B);
  ck_assert_int_eq(status, 1);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(rotate_test_1) {
  int rows1 = 2, cols1 = 3;
  matrix_t A = {0};
  s21_create_matrix(rows1, cols1, &A);
  A.matrix[0][0] = 695.0;
  A.matrix[0][1] = 930.0;
  A.matrix[0][2] = 363.0;
  A.matrix[1][0] = -60.0;
  A.matrix[1][1] = 842.0;
  A.matrix[1][2] = -291.0;
  int status = rotate_model(&A, OX, M_PI);
  ck_assert_int_eq(status, OK);
  ck_assert_double_eq_tol(A.matrix[0][0], 695, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][1], -930, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][2], -363, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][0], -60, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][1], -842, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][2], 291, 0.0000001);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(rotate_test_2) {
  int rows1 = 2, cols1 = 3;
  matrix_t A = {0};
  s21_create_matrix(rows1, cols1, &A);
  A.matrix[0][0] = 695.0;
  A.matrix[0][1] = 930.0;
  A.matrix[0][2] = 363.0;
  A.matrix[1][0] = -60.0;
  A.matrix[1][1] = 842.0;
  A.matrix[1][2] = -291.0;
  int status = rotate_model(&A, OY, M_PI_2);
  ck_assert_int_eq(status, OK);
  ck_assert_double_eq_tol(A.matrix[0][0], 363, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][1], 930, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][2], -695, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][0], -291, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][1], 842, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][2], 60, 0.0000001);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(rotate_test_3) {
  int rows1 = 2, cols1 = 3;
  matrix_t A = {0};
  s21_create_matrix(rows1, cols1, &A);
  A.matrix[0][0] = 695.0;
  A.matrix[0][1] = 930.0;
  A.matrix[0][2] = 363.0;
  A.matrix[1][0] = -60.0;
  A.matrix[1][1] = 842.0;
  A.matrix[1][2] = -291.0;
  int status = rotate_model(&A, OZ, 0);
  ck_assert_int_eq(status, OK);
  ck_assert_double_eq_tol(A.matrix[0][0], 695, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][1], 930, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[0][2], 363, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][0], -60, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][1], 842, 0.0000001);
  ck_assert_double_eq_tol(A.matrix[1][2], -291, 0.0000001);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(rotate_test_err) {
  int status = rotate_model(NULL, OZ, 0);
  ck_assert_int_eq(status, INCORRECT_MATRIX);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_create_matrix_test_1);
  tcase_add_test(tc1_1, s21_create_matrix_test_2);
  tcase_add_test(tc1_1, s21_create_matrix_test_3);
  tcase_add_test(tc1_1, s21_create_matrix_test_4);
  tcase_add_test(tc1_1, s21_create_matrix_test_5);
  tcase_add_test(tc1_1, s21_create_matrix_test_6);
  tcase_add_test(tc1_1, s21_create_matrix_test_7);
  tcase_add_test(tc1_1, equal_test_1);
  tcase_add_test(tc1_1, s21_eq_matrix_6);
  tcase_add_test(tc1_1, s21_eq_matrix_7);
  tcase_add_test(tc1_1, s21_eq_matrix_8);
  tcase_add_test(tc1_1, s21_eq_matrix_9);
  tcase_add_test(tc1_1, num_mul_test_0);
  tcase_add_test(tc1_1, s21_mul_num_1_err);
  tcase_add_test(tc1_1, rotate_test_3);
  tcase_add_test(tc1_1, rotate_test_2);
  tcase_add_test(tc1_1, rotate_test_1);
  tcase_add_test(tc1_1, rotate_test_err);
  tcase_add_test(tc1_1, sum_test_1);
  tcase_add_test(tc1_1, s21_sum_matrix_2_err);
  tcase_add_test(tc1_1, s21_sum_matrix_3_err);
  tcase_add_test(tc1_1, test_2);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
