/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

//#line 1 //"tests.check"
#include <check.h>
#include <math.h>
#include <stdint.h>
#include <stdlib.h>

#include "s21_math.h"

START_TEST(fabs_1) {
  //#line 9
  double var1 = 2;
  ck_assert_float_eq((float)s21_fabs(var1), (float)fabs(var1));
}
END_TEST

START_TEST(fabs_2) {
  //#line 12
  double var2 = -1.0;
  ck_assert_float_eq((float)s21_fabs(var2), (float)fabs(var2));
}
END_TEST

START_TEST(fabs_3) {
  //#line 15
  double var3 = 1.010;
  ck_assert_float_eq((float)s21_fabs(var3), (float)fabs(var3));
}
END_TEST

START_TEST(fabs_4) {
  //#line 18
  double var4 = -231.333333;
  ck_assert_float_eq((float)s21_fabs(var4), (float)fabs(var4));
}
END_TEST

START_TEST(fabs_5) {
  //#line 21
  double var5 = 12345.678;
  ck_assert_float_eq((float)s21_fabs(var5), (float)fabs(var5));
}
END_TEST

START_TEST(fabs_6) {
  //#line 24
  double var6 = 0.8;
  ck_assert_float_eq((float)s21_fabs(var6), (float)fabs(var6));
}
END_TEST

START_TEST(fabs_7) {
  //#line 27
  double var7 = 1.5;
  ck_assert_float_eq((float)s21_fabs(var7), (float)fabs(var7));
}
END_TEST

START_TEST(fabs_8) {
  //#line 30
  double var8 = 0.5656;
  ck_assert_float_eq((float)s21_fabs(var8), (float)fabs(var8));
}
END_TEST

START_TEST(fabs_9) {
  //#line 33
  double var9 = 0.027;
  ck_assert_float_eq((float)s21_fabs(var9), (float)fabs(var9));
}
END_TEST

START_TEST(fabs_10) {
  //#line 36
  double var10 = -0.05;
  ck_assert_float_eq((float)s21_fabs(var10), (float)fabs(var10));
}
END_TEST

START_TEST(fabs_11) {
  //#line 39
  double var11 = -0.0027;
  ck_assert_float_eq((float)s21_fabs(var11), (float)fabs(var11));
}
END_TEST

START_TEST(fabs_12) {
  //#line 42
  double var12 = 1.66666666;
  ck_assert_float_eq((float)s21_fabs(var12), (float)fabs(var12));
}
END_TEST

START_TEST(fabs_13) {
  //#line 45
  double var13 = 0.0000001;
  ck_assert_float_eq((float)s21_fabs(var13), (float)fabs(var13));
}
END_TEST

START_TEST(fabs_14) {
  //#line 48
  double var14 = 0.0;
  ck_assert_float_eq((float)s21_fabs(var14), (float)fabs(var14));
}
END_TEST

START_TEST(fabs_15) {
  //#line 51
  double var15 = -0.0;
  ck_assert_float_eq((float)s21_fabs(var15), (float)fabs(var15));
}
END_TEST

START_TEST(fabs_16) {
  //#line 54
  double var16 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_fabs(var16)), isnan((float)fabs(var16)));
}
END_TEST

START_TEST(ceil_17) {
  //#line 57
  double var17 = 2;
  ck_assert_float_eq((float)s21_ceil(var17), (float)ceil(var17));
}
END_TEST

START_TEST(ceil_18) {
  //#line 60
  double var18 = -1.0;
  ck_assert_float_eq((float)s21_ceil(var18), (float)ceil(var18));
}
END_TEST

START_TEST(ceil_19) {
  //#line 63
  double var19 = 1.010;
  ck_assert_float_eq((float)s21_ceil(var19), (float)ceil(var19));
}
END_TEST

START_TEST(ceil_20) {
  //#line 66
  double var20 = -231.333333;
  ck_assert_float_eq((float)s21_ceil(var20), (float)ceil(var20));
}
END_TEST

START_TEST(ceil_21) {
  //#line 69
  double var21 = 12345.678;
  ck_assert_float_eq((float)s21_ceil(var21), (float)ceil(var21));
}
END_TEST

START_TEST(ceil_22) {
  //#line 72
  double var22 = 0.8;
  ck_assert_float_eq((float)s21_ceil(var22), (float)ceil(var22));
}
END_TEST

START_TEST(ceil_23) {
  //#line 75
  double var23 = 1.5;
  ck_assert_float_eq((float)s21_ceil(var23), (float)ceil(var23));
}
END_TEST

START_TEST(ceil_24) {
  //#line 78
  double var24 = 0.5656;
  ck_assert_float_eq((float)s21_ceil(var24), (float)ceil(var24));
}
END_TEST

START_TEST(ceil_25) {
  //#line 81
  double var25 = 0.027;
  ck_assert_float_eq((float)s21_ceil(var25), (float)ceil(var25));
}
END_TEST

START_TEST(ceil_26) {
  //#line 84
  double var26 = -0.05;
  ck_assert_float_eq((float)s21_ceil(var26), (float)ceil(var26));
}
END_TEST

START_TEST(ceil_27) {
  //#line 87
  double var27 = -0.0027;
  ck_assert_float_eq((float)s21_ceil(var27), (float)ceil(var27));
}
END_TEST

START_TEST(ceil_28) {
  //#line 90
  double var28 = 1.66666666;
  ck_assert_float_eq((float)s21_ceil(var28), (float)ceil(var28));
}
END_TEST

START_TEST(ceil_29) {
  //#line 93
  double var29 = 0.0000001;
  ck_assert_float_eq((float)s21_ceil(var29), (float)ceil(var29));
}
END_TEST

START_TEST(ceil_30) {
  //#line 96
  double var30 = 0.0;
  ck_assert_float_eq((float)s21_ceil(var30), (float)ceil(var30));
}
END_TEST

START_TEST(ceil_31) {
  //#line 99
  double var31 = -0.0;
  ck_assert_float_eq((float)s21_ceil(var31), (float)ceil(var31));
}
END_TEST

START_TEST(ceil_32) {
  //#line 102
  double var32 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_ceil(var32)), isnan((float)ceil(var32)));
}
END_TEST

START_TEST(cos_33) {
  //#line 105
  double var33 = 2;
  ck_assert_float_eq((float)s21_cos(var33), (float)cos(var33));
}
END_TEST

START_TEST(cos_34) {
  //#line 108
  double var34 = -1.0;
  ck_assert_float_eq((float)s21_cos(var34), (float)cos(var34));
}
END_TEST

START_TEST(cos_35) {
  //#line 111
  double var35 = 1.010;
  ck_assert_float_eq((float)s21_cos(var35), (float)cos(var35));
}
END_TEST

START_TEST(cos_36) {
  //#line 114
  double var36 = -231.333333;
  ck_assert_float_eq((float)s21_cos(var36), (float)cos(var36));
}
END_TEST

START_TEST(cos_37) {
  //#line 117
  double var37 = 12345.678;
  ck_assert_float_eq((float)s21_cos(var37), (float)cos(var37));
}
END_TEST

START_TEST(cos_38) {
  //#line 120
  double var38 = 0.8;
  ck_assert_float_eq((float)s21_cos(var38), (float)cos(var38));
}
END_TEST

START_TEST(cos_39) {
  //#line 123
  double var39 = 1.5;
  ck_assert_float_eq((float)s21_cos(var39), (float)cos(var39));
}
END_TEST

START_TEST(cos_40) {
  //#line 126
  double var40 = 0.5656;
  ck_assert_float_eq((float)s21_cos(var40), (float)cos(var40));
}
END_TEST

START_TEST(cos_41) {
  //#line 129
  double var41 = 0.027;
  ck_assert_float_eq((float)s21_cos(var41), (float)cos(var41));
}
END_TEST

START_TEST(cos_42) {
  //#line 132
  double var42 = -0.05;
  ck_assert_float_eq((float)s21_cos(var42), (float)cos(var42));
}
END_TEST

START_TEST(cos_43) {
  //#line 135
  double var43 = -0.0027;
  ck_assert_float_eq((float)s21_cos(var43), (float)cos(var43));
}
END_TEST

START_TEST(cos_44) {
  //#line 138
  double var44 = 1.66666666;
  ck_assert_float_eq((float)s21_cos(var44), (float)cos(var44));
}
END_TEST

START_TEST(cos_45) {
  //#line 141
  double var45 = 0.0000001;
  ck_assert_float_eq((float)s21_cos(var45), (float)cos(var45));
}
END_TEST

START_TEST(cos_46) {
  //#line 144
  double var46 = 0.0;
  ck_assert_float_eq((float)s21_cos(var46), (float)cos(var46));
}
END_TEST

START_TEST(cos_47) {
  //#line 147
  double var47 = -0.0;
  ck_assert_float_eq((float)s21_cos(var47), (float)cos(var47));
}
END_TEST

START_TEST(cos_48) {
  //#line 150
  double var48 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_cos(var48)), isnan((float)cos(var48)));
}
END_TEST

START_TEST(exp_49) {
  //#line 153
  double var49 = 2;
  ck_assert_float_eq((float)s21_exp(var49), (float)exp(var49));
}
END_TEST

START_TEST(exp_50) {
  //#line 156
  double var50 = -1.0;
  ck_assert_float_eq((float)s21_exp(var50), (float)exp(var50));
}
END_TEST

START_TEST(exp_51) {
  //#line 159
  double var51 = 1.010;
  ck_assert_float_eq((float)s21_exp(var51), (float)exp(var51));
}
END_TEST

START_TEST(exp_52) {
  //#line 162
  double var52 = -231.333333;
  ck_assert_float_eq((float)s21_exp(var52), (float)exp(var52));
}
END_TEST

START_TEST(exp_53) {
  //#line 165
  double var53 = 12345.678;
  ck_assert_float_eq((float)s21_exp(var53), (float)exp(var53));
}
END_TEST

START_TEST(exp_54) {
  //#line 168
  double var54 = 0.8;
  ck_assert_float_eq((float)s21_exp(var54), (float)exp(var54));
}
END_TEST

START_TEST(exp_55) {
  //#line 171
  double var55 = 1.5;
  ck_assert_float_eq((float)s21_exp(var55), (float)exp(var55));
}
END_TEST

START_TEST(exp_56) {
  //#line 174
  double var56 = 0.5656;
  ck_assert_float_eq((float)s21_exp(var56), (float)exp(var56));
}
END_TEST

START_TEST(exp_57) {
  //#line 177
  double var57 = 0.027;
  ck_assert_float_eq((float)s21_exp(var57), (float)exp(var57));
}
END_TEST

START_TEST(exp_58) {
  //#line 180
  double var58 = -0.05;
  ck_assert_float_eq((float)s21_exp(var58), (float)exp(var58));
}
END_TEST

START_TEST(exp_59) {
  //#line 183
  double var59 = -0.0027;
  ck_assert_float_eq((float)s21_exp(var59), (float)exp(var59));
}
END_TEST

START_TEST(exp_60) {
  //#line 186
  double var60 = 1.66666666;
  ck_assert_float_eq((float)s21_exp(var60), (float)exp(var60));
}
END_TEST

START_TEST(exp_61) {
  //#line 189
  double var61 = 0.0000001;
  ck_assert_float_eq((float)s21_exp(var61), (float)exp(var61));
}
END_TEST

START_TEST(exp_62) {
  //#line 192
  double var62 = 0.0;
  ck_assert_float_eq((float)s21_exp(var62), (float)exp(var62));
}
END_TEST

START_TEST(exp_63) {
  //#line 195
  double var63 = -0.0;
  ck_assert_float_eq((float)s21_exp(var63), (float)exp(var63));
}
END_TEST

START_TEST(exp_64) {
  //#line 198
  double var64 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_exp(var64)), isnan((float)exp(var64)));
}
END_TEST

START_TEST(floor_65) {
  //#line 201
  double var65 = 2;
  ck_assert_float_eq((float)s21_floor(var65), (float)floor(var65));
}
END_TEST

START_TEST(floor_66) {
  //#line 204
  double var66 = -1.0;
  ck_assert_float_eq((float)s21_floor(var66), (float)floor(var66));
}
END_TEST

START_TEST(floor_67) {
  //#line 207
  double var67 = 1.010;
  ck_assert_float_eq((float)s21_floor(var67), (float)floor(var67));
}
END_TEST

START_TEST(floor_68) {
  //#line 210
  double var68 = -231.333333;
  ck_assert_float_eq((float)s21_floor(var68), (float)floor(var68));
}
END_TEST

START_TEST(floor_69) {
  //#line 213
  double var69 = 12345.678;
  ck_assert_float_eq((float)s21_floor(var69), (float)floor(var69));
}
END_TEST

START_TEST(floor_70) {
  //#line 216
  double var70 = 0.8;
  ck_assert_float_eq((float)s21_floor(var70), (float)floor(var70));
}
END_TEST

START_TEST(floor_71) {
  //#line 219
  double var71 = 1.5;
  ck_assert_float_eq((float)s21_floor(var71), (float)floor(var71));
}
END_TEST

START_TEST(floor_72) {
  //#line 222
  double var72 = 0.5656;
  ck_assert_float_eq((float)s21_floor(var72), (float)floor(var72));
}
END_TEST

START_TEST(floor_73) {
  //#line 225
  double var73 = 0.027;
  ck_assert_float_eq((float)s21_floor(var73), (float)floor(var73));
}
END_TEST

START_TEST(floor_74) {
  //#line 228
  double var74 = -0.05;
  ck_assert_float_eq((float)s21_floor(var74), (float)floor(var74));
}
END_TEST

START_TEST(floor_75) {
  //#line 231
  double var75 = -0.0027;
  ck_assert_float_eq((float)s21_floor(var75), (float)floor(var75));
}
END_TEST

START_TEST(floor_76) {
  //#line 234
  double var76 = 1.66666666;
  ck_assert_float_eq((float)s21_floor(var76), (float)floor(var76));
}
END_TEST

START_TEST(floor_77) {
  //#line 237
  double var77 = 0.0000001;
  ck_assert_float_eq((float)s21_floor(var77), (float)floor(var77));
}
END_TEST

START_TEST(floor_78) {
  //#line 240
  double var78 = 0.0;
  ck_assert_float_eq((float)s21_floor(var78), (float)floor(var78));
}
END_TEST

START_TEST(floor_79) {
  //#line 243
  double var79 = -0.0;
  ck_assert_float_eq((float)s21_floor(var79), (float)floor(var79));
}
END_TEST

START_TEST(floor_80) {
  //#line 246
  double var80 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_floor(var80)), isnan((float)floor(var80)));
}
END_TEST

START_TEST(log_81) {
  //#line 249
  double var81 = 2;
  ck_assert_float_eq((float)s21_log(var81), (float)log(var81));
}
END_TEST

START_TEST(log_82) {
  //#line 252
  double var82 = -1.0;
  ck_assert_int_eq(isnan((float)s21_log(var82)), isnan((float)log(var82)));
}
END_TEST

START_TEST(log_83) {
  //#line 255
  double var83 = 1.010;
  ck_assert_float_eq((float)s21_log(var83), (float)log(var83));
}
END_TEST

START_TEST(log_84) {
  //#line 258
  double var84 = -231.333333;
  ck_assert_int_eq(isnan((float)s21_log(var84)), isnan((float)log(var84)));
}
END_TEST

START_TEST(log_85) {
  //#line 261
  double var85 = 12345.678;
  ck_assert_float_eq((float)s21_log(var85), (float)log(var85));
}
END_TEST

START_TEST(log_86) {
  //#line 264
  double var86 = 0.8;
  ck_assert_float_eq((float)s21_log(var86), (float)log(var86));
}
END_TEST

START_TEST(log_87) {
  //#line 267
  double var87 = 1.5;
  ck_assert_float_eq((float)s21_log(var87), (float)log(var87));
}
END_TEST

START_TEST(log_88) {
  //#line 270
  double var88 = 0.5656;
  ck_assert_float_eq((float)s21_log(var88), (float)log(var88));
}
END_TEST

START_TEST(log_89) {
  //#line 273
  double var89 = 0.027;
  ck_assert_float_eq((float)s21_log(var89), (float)log(var89));
}
END_TEST

START_TEST(log_90) {
  //#line 276
  double var90 = -0.05;
  ck_assert_int_eq(isnan((float)s21_log(var90)), isnan((float)log(var90)));
}
END_TEST

START_TEST(log_91) {
  //#line 279
  double var91 = -0.0027;
  ck_assert_int_eq(isnan((float)s21_log(var91)), isnan((float)log(var91)));
}
END_TEST

START_TEST(log_92) {
  //#line 282
  double var92 = 1.66666666;
  ck_assert_float_eq((float)s21_log(var92), (float)log(var92));
}
END_TEST

START_TEST(log_93) {
  //#line 285
  double var93 = 0.0000001;
  ck_assert_float_eq((float)s21_log(var93), (float)log(var93));
}
END_TEST

START_TEST(log_94) {
  //#line 288
  double var94 = 0.0;
  ck_assert_float_eq((float)s21_log(var94), (float)log(var94));
}
END_TEST

START_TEST(log_95) {
  //#line 291
  double var95 = -0.0;
  ck_assert_float_eq((float)s21_log(var95), (float)log(var95));
}
END_TEST

START_TEST(log_96) {
  //#line 294
  double var96 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_log(var96)), isnan((float)log(var96)));
}
END_TEST

START_TEST(sin_97) {
  //#line 297
  double var97 = 2;
  ck_assert_float_eq((float)s21_sin(var97), (float)sin(var97));
}
END_TEST

START_TEST(sin_98) {
  //#line 300
  double var98 = -1.0;
  ck_assert_float_eq((float)s21_sin(var98), (float)sin(var98));
}
END_TEST

START_TEST(sin_99) {
  //#line 303
  double var99 = 1.010;
  ck_assert_float_eq((float)s21_sin(var99), (float)sin(var99));
}
END_TEST

START_TEST(sin_100) {
  //#line 306
  double var100 = -231.333333;
  ck_assert_float_eq((float)s21_sin(var100), (float)sin(var100));
}
END_TEST

START_TEST(sin_101) {
  //#line 309
  double var101 = 12345.678;
  ck_assert_float_eq((float)s21_sin(var101), (float)sin(var101));
}
END_TEST

START_TEST(sin_102) {
  //#line 312
  double var102 = 0.8;
  ck_assert_float_eq((float)s21_sin(var102), (float)sin(var102));
}
END_TEST

START_TEST(sin_103) {
  //#line 315
  double var103 = 1.5;
  ck_assert_float_eq((float)s21_sin(var103), (float)sin(var103));
}
END_TEST

START_TEST(sin_104) {
  //#line 318
  double var104 = 0.5656;
  ck_assert_float_eq((float)s21_sin(var104), (float)sin(var104));
}
END_TEST

START_TEST(sin_105) {
  //#line 321
  double var105 = 0.027;
  ck_assert_float_eq((float)s21_sin(var105), (float)sin(var105));
}
END_TEST

START_TEST(sin_106) {
  //#line 324
  double var106 = -0.05;
  ck_assert_float_eq((float)s21_sin(var106), (float)sin(var106));
}
END_TEST

START_TEST(sin_107) {
  //#line 327
  double var107 = -0.0027;
  ck_assert_float_eq((float)s21_sin(var107), (float)sin(var107));
}
END_TEST

START_TEST(sin_108) {
  //#line 330
  double var108 = 1.66666666;
  ck_assert_float_eq((float)s21_sin(var108), (float)sin(var108));
}
END_TEST

START_TEST(sin_109) {
  //#line 333
  double var109 = 0.0000001;
  ck_assert_float_eq((float)s21_sin(var109), (float)sin(var109));
}
END_TEST

START_TEST(sin_110) {
  //#line 336
  double var110 = 0.0;
  ck_assert_float_eq((float)s21_sin(var110), (float)sin(var110));
}
END_TEST

START_TEST(sin_111) {
  //#line 339
  double var111 = -0.0;
  ck_assert_float_eq((float)s21_sin(var111), (float)sin(var111));
}
END_TEST

START_TEST(sin_112) {
  //#line 342
  double var112 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_sin(var112)), isnan((float)sin(var112)));
}
END_TEST

START_TEST(sqrt_113) {
  //#line 345
  double var113 = 2;
  ck_assert_float_eq((float)s21_sqrt(var113), (float)sqrt(var113));
}
END_TEST

START_TEST(sqrt_114) {
  //#line 348
  double var114 = -1.0;
  ck_assert_int_eq(isnan((float)s21_sqrt(var114)), isnan((float)sqrt(var114)));
}
END_TEST

START_TEST(sqrt_115) {
  //#line 351
  double var115 = 1.010;
  ck_assert_float_eq((float)s21_sqrt(var115), (float)sqrt(var115));
}
END_TEST

START_TEST(sqrt_116) {
  //#line 354
  double var116 = -231.333333;
  ck_assert_int_eq(isnan((float)s21_sqrt(var116)), isnan((float)sqrt(var116)));
}
END_TEST

START_TEST(sqrt_117) {
  //#line 357
  double var117 = 12345.678;
  ck_assert_float_eq((float)s21_sqrt(var117), (float)sqrt(var117));
}
END_TEST

START_TEST(sqrt_118) {
  //#line 360
  double var118 = 0.8;
  ck_assert_float_eq((float)s21_sqrt(var118), (float)sqrt(var118));
}
END_TEST

START_TEST(sqrt_119) {
  //#line 363
  double var119 = 1.5;
  ck_assert_float_eq((float)s21_sqrt(var119), (float)sqrt(var119));
}
END_TEST

START_TEST(sqrt_120) {
  //#line 366
  double var120 = 0.5656;
  ck_assert_float_eq((float)s21_sqrt(var120), (float)sqrt(var120));
}
END_TEST

START_TEST(sqrt_121) {
  //#line 369
  double var121 = 0.027;
  ck_assert_float_eq((float)s21_sqrt(var121), (float)sqrt(var121));
}
END_TEST

START_TEST(sqrt_122) {
  //#line 372
  double var122 = -0.05;
  ck_assert_int_eq(isnan((float)s21_sqrt(var122)), isnan((float)sqrt(var122)));
}
END_TEST

START_TEST(sqrt_123) {
  //#line 375
  double var123 = -0.0027;
  ck_assert_int_eq(isnan((float)s21_sqrt(var123)), isnan((float)sqrt(var123)));
}
END_TEST

START_TEST(sqrt_124) {
  //#line 378
  double var124 = 1.66666666;
  ck_assert_float_eq((float)s21_sqrt(var124), (float)sqrt(var124));
}
END_TEST

START_TEST(sqrt_125) {
  //#line 381
  double var125 = 0.0000001;
  ck_assert_float_eq((float)s21_sqrt(var125), (float)sqrt(var125));
}
END_TEST

START_TEST(sqrt_126) {
  //#line 384
  double var126 = 0.0;
  ck_assert_float_eq((float)s21_sqrt(var126), (float)sqrt(var126));
}
END_TEST

START_TEST(sqrt_127) {
  //#line 387
  double var127 = -0.0;
  ck_assert_float_eq((float)s21_sqrt(var127), (float)sqrt(var127));
}
END_TEST

START_TEST(sqrt_128) {
  //#line 390
  double var128 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_sqrt(var128)), isnan((float)sqrt(var128)));
}
END_TEST

START_TEST(tan_129) {
  //#line 393
  double var129 = 2;
  ck_assert_float_eq((float)s21_tan(var129), (float)tan(var129));
}
END_TEST

START_TEST(tan_130) {
  //#line 396
  double var130 = -1.0;
  ck_assert_float_eq((float)s21_tan(var130), (float)tan(var130));
}
END_TEST

START_TEST(tan_131) {
  //#line 399
  double var131 = 1.010;
  ck_assert_float_eq((float)s21_tan(var131), (float)tan(var131));
}
END_TEST

START_TEST(tan_132) {
  //#line 402
  double var132 = -231.333333;
  ck_assert_float_eq((float)s21_tan(var132), (float)tan(var132));
}
END_TEST

START_TEST(tan_133) {
  //#line 405
  double var133 = 12345.678;
  ck_assert_float_eq((float)s21_tan(var133), (float)tan(var133));
}
END_TEST

START_TEST(tan_134) {
  //#line 408
  double var134 = 0.8;
  ck_assert_float_eq((float)s21_tan(var134), (float)tan(var134));
}
END_TEST

START_TEST(tan_135) {
  //#line 411
  double var135 = 1.5;
  ck_assert_float_eq((float)s21_tan(var135), (float)tan(var135));
}
END_TEST

START_TEST(tan_136) {
  //#line 414
  double var136 = 0.5656;
  ck_assert_float_eq((float)s21_tan(var136), (float)tan(var136));
}
END_TEST

START_TEST(tan_137) {
  //#line 417
  double var137 = 0.027;
  ck_assert_float_eq((float)s21_tan(var137), (float)tan(var137));
}
END_TEST

START_TEST(tan_138) {
  //#line 420
  double var138 = -0.05;
  ck_assert_float_eq((float)s21_tan(var138), (float)tan(var138));
}
END_TEST

START_TEST(tan_139) {
  //#line 423
  double var139 = -0.0027;
  ck_assert_float_eq((float)s21_tan(var139), (float)tan(var139));
}
END_TEST

START_TEST(tan_140) {
  //#line 426
  double var140 = 1.66666666;
  ck_assert_float_eq((float)s21_tan(var140), (float)tan(var140));
}
END_TEST

START_TEST(tan_141) {
  //#line 429
  double var141 = 0.0000001;
  ck_assert_float_eq((float)s21_tan(var141), (float)tan(var141));
}
END_TEST

START_TEST(tan_142) {
  //#line 432
  double var142 = 0.0;
  ck_assert_float_eq((float)s21_tan(var142), (float)tan(var142));
}
END_TEST

START_TEST(tan_143) {
  //#line 435
  double var143 = -0.0;
  ck_assert_float_eq((float)s21_tan(var143), (float)tan(var143));
}
END_TEST

START_TEST(tan_144) {
  //#line 438
  double var144 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_tan(var144)), isnan((float)tan(var144)));
}
END_TEST

START_TEST(acos_145) {
  //#line 441
  double var145 = 2;
  ck_assert_int_eq(isnan((float)s21_acos(var145)), isnan((float)acos(var145)));
}
END_TEST

START_TEST(acos_146) {
  //#line 444
  double var146 = -1.0;
  ck_assert_float_eq((float)s21_acos(var146), (float)acos(var146));
}
END_TEST

START_TEST(acos_147) {
  //#line 447
  double var147 = 1.010;
  ck_assert_int_eq(isnan((float)s21_acos(var147)), isnan((float)acos(var147)));
}
END_TEST

START_TEST(acos_148) {
  //#line 450
  double var148 = -231.333333;
  ck_assert_int_eq(isnan((float)s21_acos(var148)), isnan((float)acos(var148)));
}
END_TEST

START_TEST(acos_149) {
  //#line 453
  double var149 = 12345.678;
  ck_assert_int_eq(isnan((float)s21_acos(var149)), isnan((float)acos(var149)));
}
END_TEST

START_TEST(acos_150) {
  //#line 456
  double var150 = 0.8;
  ck_assert_float_eq((float)s21_acos(var150), (float)acos(var150));
}
END_TEST

START_TEST(acos_151) {
  //#line 459
  double var151 = 1.5;
  ck_assert_int_eq(isnan((float)s21_acos(var151)), isnan((float)acos(var151)));
}
END_TEST

START_TEST(acos_152) {
  //#line 462
  double var152 = 0.5656;
  ck_assert_float_eq((float)s21_acos(var152), (float)acos(var152));
}
END_TEST

START_TEST(acos_153) {
  //#line 465
  double var153 = 0.027;
  ck_assert_float_eq((float)s21_acos(var153), (float)acos(var153));
}
END_TEST

START_TEST(acos_154) {
  //#line 468
  double var154 = -0.05;
  ck_assert_float_eq((float)s21_acos(var154), (float)acos(var154));
}
END_TEST

START_TEST(acos_155) {
  //#line 471
  double var155 = -0.0027;
  ck_assert_float_eq((float)s21_acos(var155), (float)acos(var155));
}
END_TEST

START_TEST(acos_156) {
  //#line 474
  double var156 = 1.66666666;
  ck_assert_int_eq(isnan((float)s21_acos(var156)), isnan((float)acos(var156)));
}
END_TEST

START_TEST(acos_157) {
  //#line 477
  double var157 = 0.0000001;
  ck_assert_float_eq((float)s21_acos(var157), (float)acos(var157));
}
END_TEST

START_TEST(acos_158) {
  //#line 480
  double var158 = 0.0;
  ck_assert_float_eq((float)s21_acos(var158), (float)acos(var158));
}
END_TEST

START_TEST(acos_159) {
  //#line 483
  double var159 = -0.0;
  ck_assert_float_eq((float)s21_acos(var159), (float)acos(var159));
}
END_TEST

START_TEST(acos_160) {
  //#line 486
  double var160 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_acos(var160)), isnan((float)acos(var160)));
}
END_TEST

START_TEST(atan_161) {
  //#line 489
  double var161 = 2;
  ck_assert_float_eq((float)s21_atan(var161), (float)atan(var161));
}
END_TEST

START_TEST(atan_162) {
  //#line 492
  double var162 = -1.0;
  ck_assert_float_eq((float)s21_atan(var162), (float)atan(var162));
}
END_TEST

START_TEST(atan_163) {
  //#line 495
  double var163 = 1.010;
  ck_assert_float_eq((float)s21_atan(var163), (float)atan(var163));
}
END_TEST

START_TEST(atan_164) {
  //#line 498
  double var164 = -231.333333;
  ck_assert_float_eq((float)s21_atan(var164), (float)atan(var164));
}
END_TEST

START_TEST(atan_165) {
  //#line 501
  double var165 = 12345.678;
  ck_assert_float_eq((float)s21_atan(var165), (float)atan(var165));
}
END_TEST

START_TEST(atan_166) {
  //#line 504
  double var166 = 0.8;
  ck_assert_float_eq((float)s21_atan(var166), (float)atan(var166));
}
END_TEST

START_TEST(atan_167) {
  //#line 507
  double var167 = 1.5;
  ck_assert_float_eq((float)s21_atan(var167), (float)atan(var167));
}
END_TEST

START_TEST(atan_168) {
  //#line 510
  double var168 = 0.5656;
  ck_assert_float_eq((float)s21_atan(var168), (float)atan(var168));
}
END_TEST

START_TEST(atan_169) {
  //#line 513
  double var169 = 0.027;
  ck_assert_float_eq((float)s21_atan(var169), (float)atan(var169));
}
END_TEST

START_TEST(atan_170) {
  //#line 516
  double var170 = -0.05;
  ck_assert_float_eq((float)s21_atan(var170), (float)atan(var170));
}
END_TEST

START_TEST(atan_171) {
  //#line 519
  double var171 = -0.0027;
  ck_assert_float_eq((float)s21_atan(var171), (float)atan(var171));
}
END_TEST

START_TEST(atan_172) {
  //#line 522
  double var172 = 1.66666666;
  ck_assert_float_eq((float)s21_atan(var172), (float)atan(var172));
}
END_TEST

START_TEST(atan_173) {
  //#line 525
  double var173 = 0.0000001;
  ck_assert_float_eq((float)s21_atan(var173), (float)atan(var173));
}
END_TEST

START_TEST(atan_174) {
  //#line 528
  double var174 = 0.0;
  ck_assert_float_eq((float)s21_atan(var174), (float)atan(var174));
}
END_TEST

START_TEST(atan_175) {
  //#line 531
  double var175 = -0.0;
  ck_assert_float_eq((float)s21_atan(var175), (float)atan(var175));
}
END_TEST

START_TEST(atan_176) {
  //#line 534
  double var176 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_atan(var176)), isnan((float)atan(var176)));
}
END_TEST

START_TEST(asin_177) {
  //#line 537
  double var177 = 2;
  ck_assert_int_eq(isnan((float)s21_asin(var177)), isnan((float)asin(var177)));
}
END_TEST

START_TEST(asin_178) {
  //#line 540
  double var178 = -1.0;
  ck_assert_float_eq((float)s21_asin(var178), (float)asin(var178));
}
END_TEST

START_TEST(asin_179) {
  //#line 543
  double var179 = 1.010;
  ck_assert_int_eq(isnan((float)s21_asin(var179)), isnan((float)asin(var179)));
}
END_TEST

START_TEST(asin_180) {
  //#line 546
  double var180 = -231.333333;
  ck_assert_int_eq(isnan((float)s21_asin(var180)), isnan((float)asin(var180)));
}
END_TEST

START_TEST(asin_181) {
  //#line 549
  double var181 = 12345.678;
  ck_assert_int_eq(isnan((float)s21_asin(var181)), isnan((float)asin(var181)));
}
END_TEST

START_TEST(asin_182) {
  //#line 552
  double var182 = 0.8;
  ck_assert_float_eq((float)s21_asin(var182), (float)asin(var182));
}
END_TEST

START_TEST(asin_183) {
  //#line 555
  double var183 = 1.5;
  ck_assert_int_eq(isnan((float)s21_asin(var183)), isnan((float)asin(var183)));
}
END_TEST

START_TEST(asin_184) {
  //#line 558
  double var184 = 0.5656;
  ck_assert_float_eq((float)s21_asin(var184), (float)asin(var184));
}
END_TEST

START_TEST(asin_185) {
  //#line 561
  double var185 = 0.027;
  ck_assert_float_eq((float)s21_asin(var185), (float)asin(var185));
}
END_TEST

START_TEST(asin_186) {
  //#line 564
  double var186 = -0.05;
  ck_assert_float_eq((float)s21_asin(var186), (float)asin(var186));
}
END_TEST

START_TEST(asin_187) {
  //#line 567
  double var187 = -0.0027;
  ck_assert_float_eq((float)s21_asin(var187), (float)asin(var187));
}
END_TEST

START_TEST(asin_188) {
  //#line 570
  double var188 = 1.66666666;
  ck_assert_int_eq(isnan((float)s21_asin(var188)), isnan((float)asin(var188)));
}
END_TEST

START_TEST(asin_189) {
  //#line 573
  double var189 = 0.0000001;
  ck_assert_float_eq((float)s21_asin(var189), (float)asin(var189));
}
END_TEST

START_TEST(asin_190) {
  //#line 576
  double var190 = 0.0;
  ck_assert_float_eq((float)s21_asin(var190), (float)asin(var190));
}
END_TEST

START_TEST(asin_191) {
  //#line 579
  double var191 = -0.0;
  ck_assert_float_eq((float)s21_asin(var191), (float)asin(var191));
}
END_TEST

START_TEST(asin_192) {
  //#line 582
  double var192 = 0.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_asin(var192)), isnan((float)asin(var192)));
}
END_TEST

START_TEST(fmod_193) {
  //#line 585
  double var193 = 2;
  double var193193 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var193, var193193),
                     (float)fmod(var193, var193193));
}
END_TEST

START_TEST(fmod_194) {
  //#line 589
  double var194 = -1.0;
  double var194194 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var194, var194194),
                     (float)fmod(var194, var194194));
}
END_TEST

START_TEST(fmod_195) {
  //#line 593
  double var195 = 1.010;
  double var195195 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var195, var195195),
                     (float)fmod(var195, var195195));
}
END_TEST

START_TEST(fmod_196) {
  //#line 597
  double var196 = -231.333333;
  double var196196 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var196, var196196),
                     (float)fmod(var196, var196196));
}
END_TEST

START_TEST(fmod_197) {
  //#line 601
  double var197 = 12345.678;
  double var197197 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var197, var197197),
                     (float)fmod(var197, var197197));
}
END_TEST

START_TEST(fmod_198) {
  //#line 605
  double var198 = 0.8;
  double var198198 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var198, var198198),
                     (float)fmod(var198, var198198));
}
END_TEST

START_TEST(fmod_199) {
  //#line 609
  double var199 = 1.5;
  double var199199 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var199, var199199),
                     (float)fmod(var199, var199199));
}
END_TEST

START_TEST(fmod_200) {
  //#line 613
  double var200 = 0.5656;
  double var200200 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var200, var200200),
                     (float)fmod(var200, var200200));
}
END_TEST

START_TEST(fmod_201) {
  //#line 617
  double var201 = 0.027;
  double var201201 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var201, var201201),
                     (float)fmod(var201, var201201));
}
END_TEST

START_TEST(fmod_202) {
  //#line 621
  double var202 = -0.05;
  double var202202 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var202, var202202),
                     (float)fmod(var202, var202202));
}
END_TEST

START_TEST(fmod_203) {
  //#line 625
  double var203 = -0.0027;
  double var203203 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var203, var203203),
                     (float)fmod(var203, var203203));
}
END_TEST

START_TEST(fmod_204) {
  //#line 629
  double var204 = 1.66666666;
  double var204204 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var204, var204204),
                     (float)fmod(var204, var204204));
}
END_TEST

START_TEST(fmod_205) {
  //#line 633
  double var205 = 0.0000001;
  double var205205 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var205, var205205),
                     (float)fmod(var205, var205205));
}
END_TEST

START_TEST(fmod_206) {
  //#line 637
  double var206 = 0.0;
  double var206206 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var206, var206206),
                     (float)fmod(var206, var206206));
}
END_TEST

START_TEST(fmod_207) {
  //#line 641
  double var207 = -0.0;
  double var207207 = 2 * s21_PI;
  ck_assert_float_eq((float)s21_fmod(var207, var207207),
                     (float)fmod(var207, var207207));
}
END_TEST

START_TEST(fmod_208) {
  //#line 645
  double var208 = 0.0 / 0.0;
  double var208208 = 2 * s21_PI;
  ck_assert_int_eq(isnan((float)s21_fmod(var208, var208208)),
                   isnan((float)fmod(var208, var208208)));
}
END_TEST

START_TEST(pow_209) {
  //#line 649
  double var209 = 2;
  double var209209 = 0;
  ck_assert_float_eq((float)s21_pow(var209, var209209),
                     (float)pow(var209, var209209));
}
END_TEST

START_TEST(pow_210) {
  //#line 653
  double var210 = 2;
  double var210210 = 0.0;
  ck_assert_float_eq((float)s21_pow(var210, var210210),
                     (float)pow(var210, var210210));
}
END_TEST

START_TEST(pow_211) {
  //#line 657
  double var211 = 2;
  double var211211 = -0.0;
  ck_assert_float_eq((float)s21_pow(var211, var211211),
                     (float)pow(var211, var211211));
}
END_TEST

START_TEST(pow_213) {
  //#line 665
  double var213 = 2;
  double var213213 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var213, var213213),
                     (float)pow(var213, var213213));
}
END_TEST

START_TEST(pow_214) {
  //#line 669
  double var214 = 2;
  double var214214 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var214, var214214),
                     (float)pow(var214, var214214));
}
END_TEST

START_TEST(pow_215) {
  //#line 673
  double var215 = 2;
  double var215215 = -12.0;
  ck_assert_float_eq((float)s21_pow(var215, var215215),
                     (float)pow(var215, var215215));
}
END_TEST

START_TEST(pow_216) {
  //#line 677
  double var216 = 2;
  double var216216 = 4.8;
  ck_assert_float_eq((float)s21_pow(var216, var216216),
                     (float)pow(var216, var216216));
}
END_TEST

START_TEST(pow_217) {
  //#line 681
  double var217 = 2;
  double var217217 = -3.2;
  ck_assert_float_eq((float)s21_pow(var217, var217217),
                     (float)pow(var217, var217217));
}
END_TEST

START_TEST(pow_218) {
  //#line 685
  double var218 = -1.0;
  double var218218 = 0;
  ck_assert_float_eq((float)s21_pow(var218, var218218),
                     (float)pow(var218, var218218));
}
END_TEST

START_TEST(pow_219) {
  //#line 689
  double var219 = -1.0;
  double var219219 = 0.0;
  ck_assert_float_eq((float)s21_pow(var219, var219219),
                     (float)pow(var219, var219219));
}
END_TEST

START_TEST(pow_220) {
  //#line 693
  double var220 = -1.0;
  double var220220 = -0.0;
  ck_assert_float_eq((float)s21_pow(var220, var220220),
                     (float)pow(var220, var220220));
}
END_TEST

START_TEST(pow_222) {
  //#line 701
  double var222 = -1.0;
  double var222222 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var222, var222222),
                     (float)pow(var222, var222222));
}
END_TEST

START_TEST(pow_223) {
  //#line 705
  double var223 = -1.0;
  double var223223 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var223, var223223),
                     (float)pow(var223, var223223));
}
END_TEST

START_TEST(pow_224) {
  //#line 709
  double var224 = -1.0;
  double var224224 = -12.0;
  ck_assert_float_eq((float)s21_pow(var224, var224224),
                     (float)pow(var224, var224224));
}
END_TEST

START_TEST(pow_225) {
  //#line 713
  double var225 = -1.0;
  double var225225 = 4.8;
  ck_assert_int_eq(isnan((float)s21_pow(var225, var225225)),
                   isnan((float)pow(var225, var225225)));
}
END_TEST

START_TEST(pow_226) {
  //#line 717
  double var226 = -1.0;
  double var226226 = -3.2;
  ck_assert_int_eq(isnan((float)s21_pow(var226, var226226)),
                   isnan((float)pow(var226, var226226)));
}
END_TEST

START_TEST(pow_227) {
  //#line 721
  double var227 = 1.010;
  double var227227 = 0;
  ck_assert_float_eq((float)s21_pow(var227, var227227),
                     (float)pow(var227, var227227));
}
END_TEST

START_TEST(pow_228) {
  //#line 725
  double var228 = 1.010;
  double var228228 = 0.0;
  ck_assert_float_eq((float)s21_pow(var228, var228228),
                     (float)pow(var228, var228228));
}
END_TEST

START_TEST(pow_229) {
  //#line 729
  double var229 = 1.010;
  double var229229 = -0.0;
  ck_assert_float_eq((float)s21_pow(var229, var229229),
                     (float)pow(var229, var229229));
}
END_TEST

START_TEST(pow_231) {
  //#line 737
  double var231 = 1.010;
  double var231231 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var231, var231231),
                     (float)pow(var231, var231231));
}
END_TEST

START_TEST(pow_232) {
  //#line 741
  double var232 = 1.010;
  double var232232 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var232, var232232),
                     (float)pow(var232, var232232));
}
END_TEST

START_TEST(pow_233) {
  //#line 745
  double var233 = 1.010;
  double var233233 = -12.0;
  ck_assert_float_eq((float)s21_pow(var233, var233233),
                     (float)pow(var233, var233233));
}
END_TEST

START_TEST(pow_234) {
  //#line 749
  double var234 = 1.010;
  double var234234 = 4.8;
  ck_assert_float_eq((float)s21_pow(var234, var234234),
                     (float)pow(var234, var234234));
}
END_TEST

START_TEST(pow_235) {
  //#line 753
  double var235 = 1.010;
  double var235235 = -3.2;
  ck_assert_float_eq((float)s21_pow(var235, var235235),
                     (float)pow(var235, var235235));
}
END_TEST

START_TEST(pow_236) {
  //#line 757
  double var236 = -231.333333;
  double var236236 = 0;
  ck_assert_float_eq((float)s21_pow(var236, var236236),
                     (float)pow(var236, var236236));
}
END_TEST

START_TEST(pow_237) {
  //#line 761
  double var237 = -231.333333;
  double var237237 = 0.0;
  ck_assert_float_eq((float)s21_pow(var237, var237237),
                     (float)pow(var237, var237237));
}
END_TEST

START_TEST(pow_238) {
  //#line 765
  double var238 = -231.333333;
  double var238238 = -0.0;
  ck_assert_float_eq((float)s21_pow(var238, var238238),
                     (float)pow(var238, var238238));
}
END_TEST

START_TEST(pow_240) {
  //#line 773
  double var240 = -231.333333;
  double var240240 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var240, var240240),
                     (float)pow(var240, var240240));
}
END_TEST

START_TEST(pow_241) {
  //#line 777
  double var241 = -231.333333;
  double var241241 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var241, var241241),
                     (float)pow(var241, var241241));
}
END_TEST

START_TEST(pow_242) {
  //#line 781
  double var242 = -231.333333;
  double var242242 = -12.0;
  ck_assert_float_eq((float)s21_pow(var242, var242242),
                     (float)pow(var242, var242242));
}
END_TEST

START_TEST(pow_243) {
  //#line 785
  double var243 = -231.333333;
  double var243243 = 4.8;
  ck_assert_int_eq(isnan((float)s21_pow(var243, var243243)),
                   isnan((float)pow(var243, var243243)));
}
END_TEST

START_TEST(pow_244) {
  //#line 789
  double var244 = -231.333333;
  double var244244 = -3.2;
  ck_assert_int_eq(isnan((float)s21_pow(var244, var244244)),
                   isnan((float)pow(var244, var244244)));
}
END_TEST

START_TEST(pow_245) {
  //#line 793
  double var245 = 12345.678;
  double var245245 = 0;
  ck_assert_float_eq((float)s21_pow(var245, var245245),
                     (float)pow(var245, var245245));
}
END_TEST

START_TEST(pow_246) {
  //#line 797
  double var246 = 12345.678;
  double var246246 = 0.0;
  ck_assert_float_eq((float)s21_pow(var246, var246246),
                     (float)pow(var246, var246246));
}
END_TEST

START_TEST(pow_247) {
  //#line 801
  double var247 = 12345.678;
  double var247247 = -0.0;
  ck_assert_float_eq((float)s21_pow(var247, var247247),
                     (float)pow(var247, var247247));
}
END_TEST

START_TEST(pow_249) {
  //#line 809
  double var249 = 12345.678;
  double var249249 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var249, var249249),
                     (float)pow(var249, var249249));
}
END_TEST

START_TEST(pow_250) {
  //#line 813
  double var250 = 12345.678;
  double var250250 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var250, var250250),
                     (float)pow(var250, var250250));
}
END_TEST

START_TEST(pow_251) {
  //#line 817
  double var251 = 12345.678;
  double var251251 = -12.0;
  ck_assert_float_eq((float)s21_pow(var251, var251251),
                     (float)pow(var251, var251251));
}
END_TEST

START_TEST(pow_252) {
  //#line 821
  double var252 = 12345.678;
  double var252252 = 4.8;
  ck_assert_float_eq((float)s21_pow(var252, var252252),
                     (float)pow(var252, var252252));
}
END_TEST

START_TEST(pow_253) {
  //#line 825
  double var253 = 12345.678;
  double var253253 = -3.2;
  ck_assert_float_eq((float)s21_pow(var253, var253253),
                     (float)pow(var253, var253253));
}
END_TEST

START_TEST(pow_254) {
  //#line 829
  double var254 = 0.8;
  double var254254 = 0;
  ck_assert_float_eq((float)s21_pow(var254, var254254),
                     (float)pow(var254, var254254));
}
END_TEST

START_TEST(pow_255) {
  //#line 833
  double var255 = 0.8;
  double var255255 = 0.0;
  ck_assert_float_eq((float)s21_pow(var255, var255255),
                     (float)pow(var255, var255255));
}
END_TEST

START_TEST(pow_256) {
  //#line 837
  double var256 = 0.8;
  double var256256 = -0.0;
  ck_assert_float_eq((float)s21_pow(var256, var256256),
                     (float)pow(var256, var256256));
}
END_TEST

START_TEST(pow_258) {
  //#line 845
  double var258 = 0.8;
  double var258258 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var258, var258258),
                     (float)pow(var258, var258258));
}
END_TEST

START_TEST(pow_259) {
  //#line 849
  double var259 = 0.8;
  double var259259 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var259, var259259),
                     (float)pow(var259, var259259));
}
END_TEST

START_TEST(pow_260) {
  //#line 853
  double var260 = 0.8;
  double var260260 = -12.0;
  ck_assert_float_eq((float)s21_pow(var260, var260260),
                     (float)pow(var260, var260260));
}
END_TEST

START_TEST(pow_261) {
  //#line 857
  double var261 = 0.8;
  double var261261 = 4.8;
  ck_assert_float_eq((float)s21_pow(var261, var261261),
                     (float)pow(var261, var261261));
}
END_TEST

START_TEST(pow_262) {
  //#line 861
  double var262 = 0.8;
  double var262262 = -3.2;
  ck_assert_float_eq((float)s21_pow(var262, var262262),
                     (float)pow(var262, var262262));
}
END_TEST

START_TEST(pow_263) {
  //#line 865
  double var263 = 1.5;
  double var263263 = 0;
  ck_assert_float_eq((float)s21_pow(var263, var263263),
                     (float)pow(var263, var263263));
}
END_TEST

START_TEST(pow_264) {
  //#line 869
  double var264 = 1.5;
  double var264264 = 0.0;
  ck_assert_float_eq((float)s21_pow(var264, var264264),
                     (float)pow(var264, var264264));
}
END_TEST

START_TEST(pow_265) {
  //#line 873
  double var265 = 1.5;
  double var265265 = -0.0;
  ck_assert_float_eq((float)s21_pow(var265, var265265),
                     (float)pow(var265, var265265));
}
END_TEST

START_TEST(pow_267) {
  //#line 881
  double var267 = 1.5;
  double var267267 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var267, var267267),
                     (float)pow(var267, var267267));
}
END_TEST

START_TEST(pow_268) {
  //#line 885
  double var268 = 1.5;
  double var268268 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var268, var268268),
                     (float)pow(var268, var268268));
}
END_TEST

START_TEST(pow_269) {
  //#line 889
  double var269 = 1.5;
  double var269269 = -12.0;
  ck_assert_float_eq((float)s21_pow(var269, var269269),
                     (float)pow(var269, var269269));
}
END_TEST

START_TEST(pow_270) {
  //#line 893
  double var270 = 1.5;
  double var270270 = 4.8;
  ck_assert_float_eq((float)s21_pow(var270, var270270),
                     (float)pow(var270, var270270));
}
END_TEST

START_TEST(pow_271) {
  //#line 897
  double var271 = 1.5;
  double var271271 = -3.2;
  ck_assert_float_eq((float)s21_pow(var271, var271271),
                     (float)pow(var271, var271271));
}
END_TEST

START_TEST(pow_272) {
  //#line 901
  double var272 = 0.5656;
  double var272272 = 0;
  ck_assert_float_eq((float)s21_pow(var272, var272272),
                     (float)pow(var272, var272272));
}
END_TEST

START_TEST(pow_273) {
  //#line 905
  double var273 = 0.5656;
  double var273273 = 0.0;
  ck_assert_float_eq((float)s21_pow(var273, var273273),
                     (float)pow(var273, var273273));
}
END_TEST

START_TEST(pow_274) {
  //#line 909
  double var274 = 0.5656;
  double var274274 = -0.0;
  ck_assert_float_eq((float)s21_pow(var274, var274274),
                     (float)pow(var274, var274274));
}
END_TEST

START_TEST(pow_276) {
  //#line 917
  double var276 = 0.5656;
  double var276276 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var276, var276276),
                     (float)pow(var276, var276276));
}
END_TEST

START_TEST(pow_277) {
  //#line 921
  double var277 = 0.5656;
  double var277277 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var277, var277277),
                     (float)pow(var277, var277277));
}
END_TEST

START_TEST(pow_278) {
  //#line 925
  double var278 = 0.5656;
  double var278278 = -12.0;
  ck_assert_float_eq((float)s21_pow(var278, var278278),
                     (float)pow(var278, var278278));
}
END_TEST

START_TEST(pow_279) {
  //#line 929
  double var279 = 0.5656;
  double var279279 = 4.8;
  ck_assert_float_eq((float)s21_pow(var279, var279279),
                     (float)pow(var279, var279279));
}
END_TEST

START_TEST(pow_280) {
  //#line 933
  double var280 = 0.5656;
  double var280280 = -3.2;
  ck_assert_float_eq((float)s21_pow(var280, var280280),
                     (float)pow(var280, var280280));
}
END_TEST

START_TEST(pow_281) {
  //#line 937
  double var281 = 0.027;
  double var281281 = 0;
  ck_assert_float_eq((float)s21_pow(var281, var281281),
                     (float)pow(var281, var281281));
}
END_TEST

START_TEST(pow_282) {
  //#line 941
  double var282 = 0.027;
  double var282282 = 0.0;
  ck_assert_float_eq((float)s21_pow(var282, var282282),
                     (float)pow(var282, var282282));
}
END_TEST

START_TEST(pow_283) {
  //#line 945
  double var283 = 0.027;
  double var283283 = -0.0;
  ck_assert_float_eq((float)s21_pow(var283, var283283),
                     (float)pow(var283, var283283));
}
END_TEST

START_TEST(pow_285) {
  //#line 953
  double var285 = 0.027;
  double var285285 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var285, var285285),
                     (float)pow(var285, var285285));
}
END_TEST

START_TEST(pow_286) {
  //#line 957
  double var286 = 0.027;
  double var286286 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var286, var286286),
                     (float)pow(var286, var286286));
}
END_TEST

START_TEST(pow_287) {
  //#line 961
  double var287 = 0.027;
  double var287287 = -12.0;
  ck_assert_float_eq((float)s21_pow(var287, var287287),
                     (float)pow(var287, var287287));
}
END_TEST

START_TEST(pow_288) {
  //#line 965
  double var288 = 0.027;
  double var288288 = 4.8;
  ck_assert_float_eq((float)s21_pow(var288, var288288),
                     (float)pow(var288, var288288));
}
END_TEST

START_TEST(pow_289) {
  //#line 969
  double var289 = 0.027;
  double var289289 = -3.2;
  ck_assert_float_eq((float)s21_pow(var289, var289289),
                     (float)pow(var289, var289289));
}
END_TEST

START_TEST(pow_290) {
  //#line 973
  double var290 = -0.05;
  double var290290 = 0;
  ck_assert_float_eq((float)s21_pow(var290, var290290),
                     (float)pow(var290, var290290));
}
END_TEST

START_TEST(pow_291) {
  //#line 977
  double var291 = -0.05;
  double var291291 = 0.0;
  ck_assert_float_eq((float)s21_pow(var291, var291291),
                     (float)pow(var291, var291291));
}
END_TEST

START_TEST(pow_292) {
  //#line 981
  double var292 = -0.05;
  double var292292 = -0.0;
  ck_assert_float_eq((float)s21_pow(var292, var292292),
                     (float)pow(var292, var292292));
}
END_TEST

START_TEST(pow_294) {
  //#line 989
  double var294 = -0.05;
  double var294294 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var294, var294294),
                     (float)pow(var294, var294294));
}
END_TEST

START_TEST(pow_295) {
  //#line 993
  double var295 = -0.05;
  double var295295 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var295, var295295),
                     (float)pow(var295, var295295));
}
END_TEST

START_TEST(pow_296) {
  //#line 997
  double var296 = -0.05;
  double var296296 = -12.0;
  ck_assert_float_eq((float)s21_pow(var296, var296296),
                     (float)pow(var296, var296296));
}
END_TEST

START_TEST(pow_297) {
  //#line 1001
  double var297 = -0.05;
  double var297297 = 4.8;
  ck_assert_int_eq(isnan((float)s21_pow(var297, var297297)),
                   isnan((float)pow(var297, var297297)));
}
END_TEST

START_TEST(pow_298) {
  //#line 1005
  double var298 = -0.05;
  double var298298 = -3.2;
  ck_assert_int_eq(isnan((float)s21_pow(var298, var298298)),
                   isnan((float)pow(var298, var298298)));
}
END_TEST

START_TEST(pow_299) {
  //#line 1009
  double var299 = -0.0027;
  double var299299 = 0;
  ck_assert_float_eq((float)s21_pow(var299, var299299),
                     (float)pow(var299, var299299));
}
END_TEST

START_TEST(pow_300) {
  //#line 1013
  double var300 = -0.0027;
  double var300300 = 0.0;
  ck_assert_float_eq((float)s21_pow(var300, var300300),
                     (float)pow(var300, var300300));
}
END_TEST

START_TEST(pow_301) {
  //#line 1017
  double var301 = -0.0027;
  double var301301 = -0.0;
  ck_assert_float_eq((float)s21_pow(var301, var301301),
                     (float)pow(var301, var301301));
}
END_TEST

START_TEST(pow_303) {
  //#line 1025
  double var303 = -0.0027;
  double var303303 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var303, var303303),
                     (float)pow(var303, var303303));
}
END_TEST

START_TEST(pow_304) {
  //#line 1029
  double var304 = -0.0027;
  double var304304 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var304, var304304),
                     (float)pow(var304, var304304));
}
END_TEST

START_TEST(pow_305) {
  //#line 1033
  double var305 = -0.0027;
  double var305305 = -12.0;
  ck_assert_float_eq((float)s21_pow(var305, var305305),
                     (float)pow(var305, var305305));
}
END_TEST

START_TEST(pow_306) {
  //#line 1037
  double var306 = -0.0027;
  double var306306 = 4.8;
  ck_assert_int_eq(isnan((float)s21_pow(var306, var306306)),
                   isnan((float)pow(var306, var306306)));
}
END_TEST

START_TEST(pow_307) {
  //#line 1041
  double var307 = -0.0027;
  double var307307 = -3.2;
  ck_assert_int_eq(isnan((float)s21_pow(var307, var307307)),
                   isnan((float)pow(var307, var307307)));
}
END_TEST

START_TEST(pow_308) {
  //#line 1045
  double var308 = 1.66666666;
  double var308308 = 0;
  ck_assert_float_eq((float)s21_pow(var308, var308308),
                     (float)pow(var308, var308308));
}
END_TEST

START_TEST(pow_309) {
  //#line 1049
  double var309 = 1.66666666;
  double var309309 = 0.0;
  ck_assert_float_eq((float)s21_pow(var309, var309309),
                     (float)pow(var309, var309309));
}
END_TEST

START_TEST(pow_310) {
  //#line 1053
  double var310 = 1.66666666;
  double var310310 = -0.0;
  ck_assert_float_eq((float)s21_pow(var310, var310310),
                     (float)pow(var310, var310310));
}
END_TEST

START_TEST(pow_312) {
  //#line 1061
  double var312 = 1.66666666;
  double var312312 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var312, var312312),
                     (float)pow(var312, var312312));
}
END_TEST

START_TEST(pow_313) {
  //#line 1065
  double var313 = 1.66666666;
  double var313313 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var313, var313313),
                     (float)pow(var313, var313313));
}
END_TEST

START_TEST(pow_314) {
  //#line 1069
  double var314 = 1.66666666;
  double var314314 = -12.0;
  ck_assert_float_eq((float)s21_pow(var314, var314314),
                     (float)pow(var314, var314314));
}
END_TEST

START_TEST(pow_315) {
  //#line 1073
  double var315 = 1.66666666;
  double var315315 = 4.8;
  ck_assert_float_eq((float)s21_pow(var315, var315315),
                     (float)pow(var315, var315315));
}
END_TEST

START_TEST(pow_316) {
  //#line 1077
  double var316 = 1.66666666;
  double var316316 = -3.2;
  ck_assert_float_eq((float)s21_pow(var316, var316316),
                     (float)pow(var316, var316316));
}
END_TEST

START_TEST(pow_317) {
  //#line 1081
  double var317 = 0.0000001;
  double var317317 = 0;
  ck_assert_float_eq((float)s21_pow(var317, var317317),
                     (float)pow(var317, var317317));
}
END_TEST

START_TEST(pow_318) {
  //#line 1085
  double var318 = 0.0000001;
  double var318318 = 0.0;
  ck_assert_float_eq((float)s21_pow(var318, var318318),
                     (float)pow(var318, var318318));
}
END_TEST

START_TEST(pow_319) {
  //#line 1089
  double var319 = 0.0000001;
  double var319319 = -0.0;
  ck_assert_float_eq((float)s21_pow(var319, var319319),
                     (float)pow(var319, var319319));
}
END_TEST

START_TEST(pow_321) {
  //#line 1097
  double var321 = 0.0000001;
  double var321321 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var321, var321321),
                     (float)pow(var321, var321321));
}
END_TEST

START_TEST(pow_322) {
  //#line 1101
  double var322 = 0.0000001;
  double var322322 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var322, var322322),
                     (float)pow(var322, var322322));
}
END_TEST

START_TEST(pow_323) {
  //#line 1105
  double var323 = 0.0000001;
  double var323323 = -12.0;
  ck_assert_float_eq((float)s21_pow(var323, var323323),
                     (float)pow(var323, var323323));
}
END_TEST

START_TEST(pow_324) {
  //#line 1109
  double var324 = 0.0000001;
  double var324324 = 4.8;
  ck_assert_float_eq((float)s21_pow(var324, var324324),
                     (float)pow(var324, var324324));
}
END_TEST

START_TEST(pow_325) {
  //#line 1113
  double var325 = 0.0000001;
  double var325325 = -3.2;
  ck_assert_float_eq((float)s21_pow(var325, var325325),
                     (float)pow(var325, var325325));
}
END_TEST

START_TEST(pow_326) {
  //#line 1117
  double var326 = 0.0;
  double var326326 = 0;
  ck_assert_float_eq((float)s21_pow(var326, var326326),
                     (float)pow(var326, var326326));
}
END_TEST

START_TEST(pow_327) {
  //#line 1121
  double var327 = 0.0;
  double var327327 = 0.0;
  ck_assert_float_eq((float)s21_pow(var327, var327327),
                     (float)pow(var327, var327327));
}
END_TEST

START_TEST(pow_328) {
  //#line 1125
  double var328 = 0.0;
  double var328328 = -0.0;
  ck_assert_float_eq((float)s21_pow(var328, var328328),
                     (float)pow(var328, var328328));
}
END_TEST

START_TEST(pow_330) {
  //#line 1133
  double var330 = 0.0;
  double var330330 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var330, var330330),
                     (float)pow(var330, var330330));
}
END_TEST

START_TEST(pow_331) {
  //#line 1137
  double var331 = 0.0;
  double var331331 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var331, var331331),
                     (float)pow(var331, var331331));
}
END_TEST

START_TEST(pow_332) {
  //#line 1141
  double var332 = 0.0;
  double var332332 = -12.0;
  ck_assert_float_eq((float)s21_pow(var332, var332332),
                     (float)pow(var332, var332332));
}
END_TEST

START_TEST(pow_333) {
  //#line 1145
  double var333 = 0.0;
  double var333333 = 4.8;
  ck_assert_float_eq((float)s21_pow(var333, var333333),
                     (float)pow(var333, var333333));
}
END_TEST

START_TEST(pow_334) {
  //#line 1149
  double var334 = 0.0;
  double var334334 = -3.2;
  ck_assert_float_eq((float)s21_pow(var334, var334334),
                     (float)pow(var334, var334334));
}
END_TEST

START_TEST(pow_335) {
  //#line 1153
  double var335 = -0.0;
  double var335335 = 0;
  ck_assert_float_eq((float)s21_pow(var335, var335335),
                     (float)pow(var335, var335335));
}
END_TEST

START_TEST(pow_336) {
  //#line 1157
  double var336 = -0.0;
  double var336336 = 0.0;
  ck_assert_float_eq((float)s21_pow(var336, var336336),
                     (float)pow(var336, var336336));
}
END_TEST

START_TEST(pow_337) {
  //#line 1161
  double var337 = -0.0;
  double var337337 = -0.0;
  ck_assert_float_eq((float)s21_pow(var337, var337337),
                     (float)pow(var337, var337337));
}
END_TEST

START_TEST(pow_339) {
  //#line 1169
  double var339 = -0.0;
  double var339339 = 1.0 / 0.0;
  ck_assert_float_eq((float)s21_pow(var339, var339339),
                     (float)pow(var339, var339339));
}
END_TEST

START_TEST(pow_340) {
  //#line 1173
  double var340 = -0.0;
  double var340340 = 1.0 / -0.0;
  ck_assert_float_eq((float)s21_pow(var340, var340340),
                     (float)pow(var340, var340340));
}
END_TEST

START_TEST(pow_341) {
  //#line 1177
  double var341 = -0.0;
  double var341341 = -12.0;
  ck_assert_float_eq((float)s21_pow(var341, var341341),
                     (float)pow(var341, var341341));
}
END_TEST

START_TEST(pow_342) {
  //#line 1181
  double var342 = -0.0;
  double var342342 = 4.8;
  ck_assert_float_eq((float)s21_pow(var342, var342342),
                     (float)pow(var342, var342342));
}
END_TEST

START_TEST(pow_343) {
  //#line 1185
  double var343 = -0.0;
  double var343343 = -3.2;
  ck_assert_float_eq((float)s21_pow(var343, var343343),
                     (float)pow(var343, var343343));
}
END_TEST

START_TEST(pow_344) {
  //#line 1189
  double var344 = 0.0 / 0.0;
  double var344344 = 0;
  ck_assert_float_eq((float)s21_pow(var344, var344344),
                     (float)pow(var344, var344344));
}
END_TEST

START_TEST(pow_345) {
  //#line 1193
  double var345 = 0.0 / 0.0;
  double var345345 = 0.0;
  ck_assert_float_eq((float)s21_pow(var345, var345345),
                     (float)pow(var345, var345345));
}
END_TEST

START_TEST(pow_346) {
  //#line 1197
  double var346 = 0.0 / 0.0;
  double var346346 = -0.0;
  ck_assert_float_eq((float)s21_pow(var346, var346346),
                     (float)pow(var346, var346346));
}
END_TEST

START_TEST(pow_348) {
  //#line 1205
  double var348 = 0.0 / 0.0;
  double var348348 = 1.0 / 0.0;
  ck_assert_int_eq(isnan((float)s21_pow(var348, var348348)),
                   isnan((float)pow(var348, var348348)));
}
END_TEST

START_TEST(pow_349) {
  //#line 1209
  double var349 = 0.0 / 0.0;
  double var349349 = 1.0 / -0.0;
  ck_assert_int_eq(isnan((float)s21_pow(var349, var349349)),
                   isnan((float)pow(var349, var349349)));
}
END_TEST

START_TEST(pow_351) {
  //#line 1217
  double var351 = 0.0 / 0.0;
  double var351351 = 4.8;
  ck_assert_int_eq(isnan((float)s21_pow(var351, var351351)),
                   isnan((float)pow(var351, var351351)));
}
END_TEST

START_TEST(pow_352) {
  //#line 1221
  double var352 = 0.0 / 0.0;
  double var352352 = -3.2;
  ck_assert_int_eq(isnan((float)s21_pow(var352, var352352)),
                   isnan((float)pow(var352, var352352)));
}
END_TEST

START_TEST(abs_353) {
  //#line 1225
  int var353 = 0;
  ck_assert_int_eq(s21_abs(var353), abs(var353));
}
END_TEST

START_TEST(abs_354) {
  //#line 1228
  int var354 = 1;
  ck_assert_int_eq(s21_abs(var354), abs(var354));
}
END_TEST

START_TEST(abs_355) {
  //#line 1231
  int var355 = 781263;
  ck_assert_int_eq(s21_abs(var355), abs(var355));
}
END_TEST

START_TEST(abs_356) {
  //#line 1234
  int var356 = -4771;
  ck_assert_int_eq(s21_abs(var356), abs(var356));
}
END_TEST

START_TEST(abs_357) {
  //#line 1237
  int var357 = -77;
  ck_assert_int_eq(s21_abs(var357), abs(var357));
}
END_TEST

START_TEST(abs_358) {
  //#line 1240
  int var358 = 125;
  ck_assert_int_eq(s21_abs(var358), abs(var358));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, fabs_1);
  tcase_add_test(tc1_1, fabs_2);
  tcase_add_test(tc1_1, fabs_3);
  tcase_add_test(tc1_1, fabs_4);
  tcase_add_test(tc1_1, fabs_5);
  tcase_add_test(tc1_1, fabs_6);
  tcase_add_test(tc1_1, fabs_7);
  tcase_add_test(tc1_1, fabs_8);
  tcase_add_test(tc1_1, fabs_9);
  tcase_add_test(tc1_1, fabs_10);
  tcase_add_test(tc1_1, fabs_11);
  tcase_add_test(tc1_1, fabs_12);
  tcase_add_test(tc1_1, fabs_13);
  tcase_add_test(tc1_1, fabs_14);
  tcase_add_test(tc1_1, fabs_15);
  tcase_add_test(tc1_1, fabs_16);
  tcase_add_test(tc1_1, ceil_17);
  tcase_add_test(tc1_1, ceil_18);
  tcase_add_test(tc1_1, ceil_19);
  tcase_add_test(tc1_1, ceil_20);
  tcase_add_test(tc1_1, ceil_21);
  tcase_add_test(tc1_1, ceil_22);
  tcase_add_test(tc1_1, ceil_23);
  tcase_add_test(tc1_1, ceil_24);
  tcase_add_test(tc1_1, ceil_25);
  tcase_add_test(tc1_1, ceil_26);
  tcase_add_test(tc1_1, ceil_27);
  tcase_add_test(tc1_1, ceil_28);
  tcase_add_test(tc1_1, ceil_29);
  tcase_add_test(tc1_1, ceil_30);
  tcase_add_test(tc1_1, ceil_31);
  tcase_add_test(tc1_1, ceil_32);
  tcase_add_test(tc1_1, cos_33);
  tcase_add_test(tc1_1, cos_34);
  tcase_add_test(tc1_1, cos_35);
  tcase_add_test(tc1_1, cos_36);
  tcase_add_test(tc1_1, cos_37);
  tcase_add_test(tc1_1, cos_38);
  tcase_add_test(tc1_1, cos_39);
  tcase_add_test(tc1_1, cos_40);
  tcase_add_test(tc1_1, cos_41);
  tcase_add_test(tc1_1, cos_42);
  tcase_add_test(tc1_1, cos_43);
  tcase_add_test(tc1_1, cos_44);
  tcase_add_test(tc1_1, cos_45);
  tcase_add_test(tc1_1, cos_46);
  tcase_add_test(tc1_1, cos_47);
  tcase_add_test(tc1_1, cos_48);
  tcase_add_test(tc1_1, exp_49);
  tcase_add_test(tc1_1, exp_50);
  tcase_add_test(tc1_1, exp_51);
  tcase_add_test(tc1_1, exp_52);
  tcase_add_test(tc1_1, exp_53);
  tcase_add_test(tc1_1, exp_54);
  tcase_add_test(tc1_1, exp_55);
  tcase_add_test(tc1_1, exp_56);
  tcase_add_test(tc1_1, exp_57);
  tcase_add_test(tc1_1, exp_58);
  tcase_add_test(tc1_1, exp_59);
  tcase_add_test(tc1_1, exp_60);
  tcase_add_test(tc1_1, exp_61);
  tcase_add_test(tc1_1, exp_62);
  tcase_add_test(tc1_1, exp_63);
  tcase_add_test(tc1_1, exp_64);
  tcase_add_test(tc1_1, floor_65);
  tcase_add_test(tc1_1, floor_66);
  tcase_add_test(tc1_1, floor_67);
  tcase_add_test(tc1_1, floor_68);
  tcase_add_test(tc1_1, floor_69);
  tcase_add_test(tc1_1, floor_70);
  tcase_add_test(tc1_1, floor_71);
  tcase_add_test(tc1_1, floor_72);
  tcase_add_test(tc1_1, floor_73);
  tcase_add_test(tc1_1, floor_74);
  tcase_add_test(tc1_1, floor_75);
  tcase_add_test(tc1_1, floor_76);
  tcase_add_test(tc1_1, floor_77);
  tcase_add_test(tc1_1, floor_78);
  tcase_add_test(tc1_1, floor_79);
  tcase_add_test(tc1_1, floor_80);
  tcase_add_test(tc1_1, log_81);
  tcase_add_test(tc1_1, log_82);
  tcase_add_test(tc1_1, log_83);
  tcase_add_test(tc1_1, log_84);
  tcase_add_test(tc1_1, log_85);
  tcase_add_test(tc1_1, log_86);
  tcase_add_test(tc1_1, log_87);
  tcase_add_test(tc1_1, log_88);
  tcase_add_test(tc1_1, log_89);
  tcase_add_test(tc1_1, log_90);
  tcase_add_test(tc1_1, log_91);
  tcase_add_test(tc1_1, log_92);
  tcase_add_test(tc1_1, log_93);
  tcase_add_test(tc1_1, log_94);
  tcase_add_test(tc1_1, log_95);
  tcase_add_test(tc1_1, log_96);
  tcase_add_test(tc1_1, sin_97);
  tcase_add_test(tc1_1, sin_98);
  tcase_add_test(tc1_1, sin_99);
  tcase_add_test(tc1_1, sin_100);
  tcase_add_test(tc1_1, sin_101);
  tcase_add_test(tc1_1, sin_102);
  tcase_add_test(tc1_1, sin_103);
  tcase_add_test(tc1_1, sin_104);
  tcase_add_test(tc1_1, sin_105);
  tcase_add_test(tc1_1, sin_106);
  tcase_add_test(tc1_1, sin_107);
  tcase_add_test(tc1_1, sin_108);
  tcase_add_test(tc1_1, sin_109);
  tcase_add_test(tc1_1, sin_110);
  tcase_add_test(tc1_1, sin_111);
  tcase_add_test(tc1_1, sin_112);
  tcase_add_test(tc1_1, sqrt_113);
  tcase_add_test(tc1_1, sqrt_114);
  tcase_add_test(tc1_1, sqrt_115);
  tcase_add_test(tc1_1, sqrt_116);
  tcase_add_test(tc1_1, sqrt_117);
  tcase_add_test(tc1_1, sqrt_118);
  tcase_add_test(tc1_1, sqrt_119);
  tcase_add_test(tc1_1, sqrt_120);
  tcase_add_test(tc1_1, sqrt_121);
  tcase_add_test(tc1_1, sqrt_122);
  tcase_add_test(tc1_1, sqrt_123);
  tcase_add_test(tc1_1, sqrt_124);
  tcase_add_test(tc1_1, sqrt_125);
  tcase_add_test(tc1_1, sqrt_126);
  tcase_add_test(tc1_1, sqrt_127);
  tcase_add_test(tc1_1, sqrt_128);
  tcase_add_test(tc1_1, tan_129);
  tcase_add_test(tc1_1, tan_130);
  tcase_add_test(tc1_1, tan_131);
  tcase_add_test(tc1_1, tan_132);
  tcase_add_test(tc1_1, tan_133);
  tcase_add_test(tc1_1, tan_134);
  tcase_add_test(tc1_1, tan_135);
  tcase_add_test(tc1_1, tan_136);
  tcase_add_test(tc1_1, tan_137);
  tcase_add_test(tc1_1, tan_138);
  tcase_add_test(tc1_1, tan_139);
  tcase_add_test(tc1_1, tan_140);
  tcase_add_test(tc1_1, tan_141);
  tcase_add_test(tc1_1, tan_142);
  tcase_add_test(tc1_1, tan_143);
  tcase_add_test(tc1_1, tan_144);
  tcase_add_test(tc1_1, acos_145);
  tcase_add_test(tc1_1, acos_146);
  tcase_add_test(tc1_1, acos_147);
  tcase_add_test(tc1_1, acos_148);
  tcase_add_test(tc1_1, acos_149);
  tcase_add_test(tc1_1, acos_150);
  tcase_add_test(tc1_1, acos_151);
  tcase_add_test(tc1_1, acos_152);
  tcase_add_test(tc1_1, acos_153);
  tcase_add_test(tc1_1, acos_154);
  tcase_add_test(tc1_1, acos_155);
  tcase_add_test(tc1_1, acos_156);
  tcase_add_test(tc1_1, acos_157);
  tcase_add_test(tc1_1, acos_158);
  tcase_add_test(tc1_1, acos_159);
  tcase_add_test(tc1_1, acos_160);
  tcase_add_test(tc1_1, atan_161);
  tcase_add_test(tc1_1, atan_162);
  tcase_add_test(tc1_1, atan_163);
  tcase_add_test(tc1_1, atan_164);
  tcase_add_test(tc1_1, atan_165);
  tcase_add_test(tc1_1, atan_166);
  tcase_add_test(tc1_1, atan_167);
  tcase_add_test(tc1_1, atan_168);
  tcase_add_test(tc1_1, atan_169);
  tcase_add_test(tc1_1, atan_170);
  tcase_add_test(tc1_1, atan_171);
  tcase_add_test(tc1_1, atan_172);
  tcase_add_test(tc1_1, atan_173);
  tcase_add_test(tc1_1, atan_174);
  tcase_add_test(tc1_1, atan_175);
  tcase_add_test(tc1_1, atan_176);
  tcase_add_test(tc1_1, asin_177);
  tcase_add_test(tc1_1, asin_178);
  tcase_add_test(tc1_1, asin_179);
  tcase_add_test(tc1_1, asin_180);
  tcase_add_test(tc1_1, asin_181);
  tcase_add_test(tc1_1, asin_182);
  tcase_add_test(tc1_1, asin_183);
  tcase_add_test(tc1_1, asin_184);
  tcase_add_test(tc1_1, asin_185);
  tcase_add_test(tc1_1, asin_186);
  tcase_add_test(tc1_1, asin_187);
  tcase_add_test(tc1_1, asin_188);
  tcase_add_test(tc1_1, asin_189);
  tcase_add_test(tc1_1, asin_190);
  tcase_add_test(tc1_1, asin_191);
  tcase_add_test(tc1_1, asin_192);
  tcase_add_test(tc1_1, fmod_193);
  tcase_add_test(tc1_1, fmod_194);
  tcase_add_test(tc1_1, fmod_195);
  tcase_add_test(tc1_1, fmod_196);
  tcase_add_test(tc1_1, fmod_197);
  tcase_add_test(tc1_1, fmod_198);
  tcase_add_test(tc1_1, fmod_199);
  tcase_add_test(tc1_1, fmod_200);
  tcase_add_test(tc1_1, fmod_201);
  tcase_add_test(tc1_1, fmod_202);
  tcase_add_test(tc1_1, fmod_203);
  tcase_add_test(tc1_1, fmod_204);
  tcase_add_test(tc1_1, fmod_205);
  tcase_add_test(tc1_1, fmod_206);
  tcase_add_test(tc1_1, fmod_207);
  tcase_add_test(tc1_1, fmod_208);
  tcase_add_test(tc1_1, pow_209);
  tcase_add_test(tc1_1, pow_210);
  tcase_add_test(tc1_1, pow_211);
  tcase_add_test(tc1_1, pow_213);
  tcase_add_test(tc1_1, pow_214);
  tcase_add_test(tc1_1, pow_215);
  tcase_add_test(tc1_1, pow_216);
  tcase_add_test(tc1_1, pow_217);
  tcase_add_test(tc1_1, pow_218);
  tcase_add_test(tc1_1, pow_219);
  tcase_add_test(tc1_1, pow_220);
  tcase_add_test(tc1_1, pow_222);
  tcase_add_test(tc1_1, pow_223);
  tcase_add_test(tc1_1, pow_224);
  tcase_add_test(tc1_1, pow_225);
  tcase_add_test(tc1_1, pow_226);
  tcase_add_test(tc1_1, pow_227);
  tcase_add_test(tc1_1, pow_228);
  tcase_add_test(tc1_1, pow_229);
  tcase_add_test(tc1_1, pow_231);
  tcase_add_test(tc1_1, pow_232);
  tcase_add_test(tc1_1, pow_233);
  tcase_add_test(tc1_1, pow_234);
  tcase_add_test(tc1_1, pow_235);
  tcase_add_test(tc1_1, pow_236);
  tcase_add_test(tc1_1, pow_237);
  tcase_add_test(tc1_1, pow_238);
  tcase_add_test(tc1_1, pow_240);
  tcase_add_test(tc1_1, pow_241);
  tcase_add_test(tc1_1, pow_242);
  tcase_add_test(tc1_1, pow_243);
  tcase_add_test(tc1_1, pow_244);
  tcase_add_test(tc1_1, pow_245);
  tcase_add_test(tc1_1, pow_246);
  tcase_add_test(tc1_1, pow_247);
  tcase_add_test(tc1_1, pow_249);
  tcase_add_test(tc1_1, pow_250);
  tcase_add_test(tc1_1, pow_251);
  tcase_add_test(tc1_1, pow_252);
  tcase_add_test(tc1_1, pow_253);
  tcase_add_test(tc1_1, pow_254);
  tcase_add_test(tc1_1, pow_255);
  tcase_add_test(tc1_1, pow_256);
  tcase_add_test(tc1_1, pow_258);
  tcase_add_test(tc1_1, pow_259);
  tcase_add_test(tc1_1, pow_260);
  tcase_add_test(tc1_1, pow_261);
  tcase_add_test(tc1_1, pow_262);
  tcase_add_test(tc1_1, pow_263);
  tcase_add_test(tc1_1, pow_264);
  tcase_add_test(tc1_1, pow_265);
  tcase_add_test(tc1_1, pow_267);
  tcase_add_test(tc1_1, pow_268);
  tcase_add_test(tc1_1, pow_269);
  tcase_add_test(tc1_1, pow_270);
  tcase_add_test(tc1_1, pow_271);
  tcase_add_test(tc1_1, pow_272);
  tcase_add_test(tc1_1, pow_273);
  tcase_add_test(tc1_1, pow_274);
  tcase_add_test(tc1_1, pow_276);
  tcase_add_test(tc1_1, pow_277);
  tcase_add_test(tc1_1, pow_278);
  tcase_add_test(tc1_1, pow_279);
  tcase_add_test(tc1_1, pow_280);
  tcase_add_test(tc1_1, pow_281);
  tcase_add_test(tc1_1, pow_282);
  tcase_add_test(tc1_1, pow_283);
  tcase_add_test(tc1_1, pow_285);
  tcase_add_test(tc1_1, pow_286);
  tcase_add_test(tc1_1, pow_287);
  tcase_add_test(tc1_1, pow_288);
  tcase_add_test(tc1_1, pow_289);
  tcase_add_test(tc1_1, pow_290);
  tcase_add_test(tc1_1, pow_291);
  tcase_add_test(tc1_1, pow_292);
  tcase_add_test(tc1_1, pow_294);
  tcase_add_test(tc1_1, pow_295);
  tcase_add_test(tc1_1, pow_296);
  tcase_add_test(tc1_1, pow_297);
  tcase_add_test(tc1_1, pow_298);
  tcase_add_test(tc1_1, pow_299);
  tcase_add_test(tc1_1, pow_300);
  tcase_add_test(tc1_1, pow_301);
  tcase_add_test(tc1_1, pow_303);
  tcase_add_test(tc1_1, pow_304);
  tcase_add_test(tc1_1, pow_305);
  tcase_add_test(tc1_1, pow_306);
  tcase_add_test(tc1_1, pow_307);
  tcase_add_test(tc1_1, pow_308);
  tcase_add_test(tc1_1, pow_309);
  tcase_add_test(tc1_1, pow_310);
  tcase_add_test(tc1_1, pow_312);
  tcase_add_test(tc1_1, pow_313);
  tcase_add_test(tc1_1, pow_314);
  tcase_add_test(tc1_1, pow_315);
  tcase_add_test(tc1_1, pow_316);
  tcase_add_test(tc1_1, pow_317);
  tcase_add_test(tc1_1, pow_318);
  tcase_add_test(tc1_1, pow_319);
  tcase_add_test(tc1_1, pow_321);
  tcase_add_test(tc1_1, pow_322);
  tcase_add_test(tc1_1, pow_323);
  tcase_add_test(tc1_1, pow_324);
  tcase_add_test(tc1_1, pow_325);
  tcase_add_test(tc1_1, pow_326);
  tcase_add_test(tc1_1, pow_327);
  tcase_add_test(tc1_1, pow_328);
  tcase_add_test(tc1_1, pow_330);
  tcase_add_test(tc1_1, pow_331);
  tcase_add_test(tc1_1, pow_332);
  tcase_add_test(tc1_1, pow_333);
  tcase_add_test(tc1_1, pow_334);
  tcase_add_test(tc1_1, pow_335);
  tcase_add_test(tc1_1, pow_336);
  tcase_add_test(tc1_1, pow_337);
  tcase_add_test(tc1_1, pow_339);
  tcase_add_test(tc1_1, pow_340);
  tcase_add_test(tc1_1, pow_341);
  tcase_add_test(tc1_1, pow_342);
  tcase_add_test(tc1_1, pow_343);
  tcase_add_test(tc1_1, pow_344);
  tcase_add_test(tc1_1, pow_345);
  tcase_add_test(tc1_1, pow_346);
  tcase_add_test(tc1_1, pow_348);
  tcase_add_test(tc1_1, pow_349);
  tcase_add_test(tc1_1, pow_351);
  tcase_add_test(tc1_1, pow_352);
  tcase_add_test(tc1_1, abs_353);
  tcase_add_test(tc1_1, abs_354);
  tcase_add_test(tc1_1, abs_355);
  tcase_add_test(tc1_1, abs_356);
  tcase_add_test(tc1_1, abs_357);
  tcase_add_test(tc1_1, abs_358);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
